// AUTO-GENERATED by generate_sdk.py from CASC dump — do not edit manually
#pragma once

#include <cstdint>

namespace ow_v2 {
namespace gen {

inline const char* HeroNameZhCN(uint32_t hero_id) noexcept {
    switch (hero_id) {
    case 0x2: return "死神";
    case 0x3: return "猎空";
    case 0x4: return "天使";
    case 0x5: return "半藏";
    case 0x6: return "托比昂";
    case 0x7: return "莱因哈特";
    case 0x8: return "法老之鹰";
    case 0x9: return "温斯顿";
    case 0xA: return "黑百合";
    case 0x15: return "堡垒";
    case 0x16: return "秩序之光";
    case 0x20: return "禅雅塔";
    case 0x29: return "源氏";
    case 0x40: return "路霸";
    case 0x42: return "卡西迪";
    case 0x65: return "狂鼠";
    case 0x68: return "查莉娅";
    case 0x6E: return "士兵：76";
    case 0x79: return "卢西奥";
    case 0x7A: return "D.Va";
    case 0xDD: return "美";
    case 0x12E: return "黑影";
    case 0x12F: return "末日铁拳";
    case 0x13B: return "安娜";
    case 0x13E: return "奥丽莎";
    case 0x195: return "布丽吉塔";
    case 0x1A2: return "莫伊拉";
    case 0x1CA: return "破坏球";
    case 0x1EC: return "索杰恩";
    case 0x200: return "艾什";
    case 0x206: return "回声";
    case 0x221: return "巴蒂斯特";
    case 0x231: return "雾子";
    case 0x236: return "渣客女王";
    case 0x23B: return "西格玛";
    case 0x28D: return "拉玛刹";
    case 0x291: return "生命之梭";
    case 0x30A: return "毛加";
    case 0x31C: return "伊拉锐";
    case 0x32A: return "弗蕾娅";
    case 0x32B: return "探奇";
    case 0x362: return "骇灾";
    case 0x365: return "朱诺";
    case 0x3C3: return "无漾";
    case 0x472: return "斩仇";
    case 0x4C4: return "金驭";
    case 0x4D8: return "埃姆雷";
    case 0x4DD: return "安燃";
    case 0x4E3: return "瑞稀";
    case 0x516: return "飞天猫";
    default: return "?";
    }
}

struct AbilityInfo {
    const char* name;
    const char* category;
    const char* button;
};

// 死神 (0x2)
inline constexpr AbilityInfo kAbilities_2[] = {
    {"死亡绽放", "UltimateAbility", "技能 3"},
    {"地狱火霰弹枪", "Weapon", "主要攻击模式"},
    {"暗影步", "Ability", "技能 2"},
    {"收割", "PassiveAbility", ""},
    {"幽灵形态", "Ability", "技能 1"},
    {"恐怖扳机", "Ability", "辅助攻击模式"},
};

// 猎空 (0x3)
inline constexpr AbilityInfo kAbilities_3[] = {
    {"闪现", "Ability", "技能 1"},
    {"闪回", "Ability", "技能 2"},
    {"脉冲炸弹", "UltimateAbility", "技能 3"},
    {"脉冲双枪", "Weapon", "主要攻击模式"},
};

// 天使 (0x4)
inline constexpr AbilityInfo kAbilities_4[] = {
    {"天使之杖", "Weapon", "主要攻击模式"},
    {"守护天使", "Ability", "技能 1"},
    {"天使之杖", "Weapon", "辅助攻击模式"},
    {"重生", "Ability", "技能 2"},
    {"快速治疗", "Ability", "装填弹药"},
    {"天使冲击枪", "Weapon", "主要攻击模式"},
    {"天使降临", "PassiveAbility", "跳跃"},
    {"迅捷恢复", "PassiveAbility", ""},
    {"女武神", "UltimateAbility", "技能 3"},
};

// 半藏 (0x5)
inline constexpr AbilityInfo kAbilities_5[] = {
    {"竜", "UltimateAbility", "技能 3"},
    {"音", "Ability", "技能 1"},
    {"岚", "Ability", "技能 2"},
    {"风", "Weapon", "主要攻击模式"},
    {"攀", "PassiveAbility", "跳跃"},
    {"跃", "Ability", "跳跃"},
};

// 托比昂 (0x6)
inline constexpr AbilityInfo kAbilities_6[] = {
    {"部署炮台", "Ability", "技能 1"},
    {"热力过载", "Ability", "技能 2"},
    {"熔火核心", "UltimateAbility", "技能 3"},
    {"铆钉枪", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"锻造锤", "Weapon", "主要攻击模式"},
};

// 莱因哈特 (0x7)
inline constexpr AbilityInfo kAbilities_7[] = {
    {"冲锋", "Ability", "技能 1"},
    {"裂地猛击", "UltimateAbility", "技能 3"},
    {"烈焰打击", "Ability", "技能 2"},
    {"火箭重锤", "Weapon", "主要攻击模式"},
    {"屏障力场", "Ability", "辅助攻击模式"},
    {"职责：重装", "PassiveAbility", ""},
};

// 法老之鹰 (0x8)
inline constexpr AbilityInfo kAbilities_8[] = {
    {"火箭弹幕", "UltimateAbility", "技能 3"},
    {"推进背包", "Ability", "技能 1"},
    {"震荡冲击", "Ability", "技能 2"},
    {"火箭发射器", "Weapon", "主要攻击模式"},
    {"悬浮背包", "PassiveAbility", "跳跃"},
    {"疾冲背包", "Ability", "辅助攻击模式"},
};

// 温斯顿 (0x9)
inline constexpr AbilityInfo kAbilities_9[] = {
    {"喷射背包", "Ability", "技能 1"},
    {"原始暴怒", "UltimateAbility", "技能 3"},
    {"屏障发射器", "Ability", "技能 2"},
    {"特斯拉炮", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"职责：重装", "PassiveAbility", ""},
};

// 黑百合 (0xA)
inline constexpr AbilityInfo kAbilities_A[] = {
    {"抓钩", "Ability", "技能 1"},
    {"红外侦测", "UltimateAbility", "技能 3"},
    {"剧毒诡雷", "Ability", "技能 2"},
    {"黑百合之吻", "Weapon", "主要攻击模式"},
    {"瞄准射击", "Weapon", "辅助攻击模式"},
};

// 堡垒 (0x15)
inline constexpr AbilityInfo kAbilities_15[] = {
    {"A-36战术榴弹", "Ability", "辅助攻击模式"},
    {"切换模式", "Ability", "技能 1"},
    {"侦察模式", "Weapon", "主要攻击模式"},
    {"强攻模式", "Weapon", "主要攻击模式"},
    {"火炮模式", "UltimateAbility", "技能 3"},
    {"抗击装甲", "PassiveAbility", ""},
};

// 秩序之光 (0x16)
inline constexpr AbilityInfo kAbilities_16[] = {
    {"光子发射器", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"哨戒炮", "Ability", "技能 1"},
    {"光子屏障", "UltimateAbility", "技能 3"},
    {"传送面板", "Ability", "技能 2"},
};

// 禅雅塔 (0x20)
inline constexpr AbilityInfo kAbilities_20[] = {
    {"灭", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"乱", "Ability", "技能 2"},
    {"谐", "Ability", "技能 1"},
    {"圣", "UltimateAbility", "技能 3"},
    {"蹬", "PassiveAbility", "快速近身攻击"},
};

// 源氏 (0x29)
inline constexpr AbilityInfo kAbilities_29[] = {
    {"斩", "UltimateAbility", "技能 3"},
    {"闪", "Ability", "技能 2"},
    {"影", "Ability", "技能 1"},
    {"镖", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"灵", "PassiveAbility", "跳跃"},
};

// 路霸 (0x40)
inline constexpr AbilityInfo kAbilities_40[] = {
    {"鸡飞狗跳", "UltimateAbility", "技能 3"},
    {"爆裂枪", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"链钩", "Ability", "技能 1"},
    {"呼吸器", "Ability", "技能 2"},
    {"职责：重装", "PassiveAbility", ""},
};

// 卡西迪 (0x42)
inline constexpr AbilityInfo kAbilities_42[] = {
    {"神射手", "UltimateAbility", "技能 3"},
    {"战术翻滚", "Ability", "技能 1"},
    {"闪光弹", "Ability", "技能 2"},
    {"维和者", "Weapon", "主要攻击模式"},
    {"连射", "Weapon", "辅助攻击模式"},
};

// 狂鼠 (0x65)
inline constexpr AbilityInfo kAbilities_65[] = {
    {"榴弹发射器", "Weapon", "主要攻击模式"},
    {"震荡地雷", "Ability", "技能 1"},
    {"捕兽夹", "Ability", "技能 2"},
    {"炸弹轮胎", "UltimateAbility", "技能 3"},
    {"临别礼物", "PassiveAbility", ""},
};

// 查莉娅 (0x68)
inline constexpr AbilityInfo kAbilities_68[] = {
    {"重力喷涌", "UltimateAbility", "技能 3"},
    {"粒子屏障", "Ability", "技能 1"},
    {"投射屏障", "Ability", "技能 2"},
    {"粒子炮", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"能量转换", "PassiveAbility", ""},
    {"职责：重装", "PassiveAbility", ""},
};

// 士兵：76 (0x6E)
inline constexpr AbilityInfo kAbilities_6E[] = {
    {"疾跑", "Ability", "技能 1"},
    {"生物力场", "Ability", "技能 2"},
    {"重型脉冲步枪", "Weapon", "主要攻击模式"},
    {"螺旋飞弹", "Ability", "辅助攻击模式"},
    {"战术目镜", "UltimateAbility", "技能 3"},
};

// 卢西奥 (0x79)
inline constexpr AbilityInfo kAbilities_79[] = {
    {"切歌", "Ability", "技能 1"},
    {"强音", "Ability", "技能 2"},
    {"音速扩音器", "Weapon", "主要攻击模式"},
    {"音波", "Ability", "辅助攻击模式"},
    {"音障", "UltimateAbility", "技能 3"},
    {"滑墙", "PassiveAbility", "跳跃"},
};

// D.Va (0x7A)
inline constexpr AbilityInfo kAbilities_7A[] = {
    {"推进器", "Ability", "技能 1"},
    {"防御矩阵", "Ability", "辅助攻击模式"},
    {"自毁", "UltimateAbility", "技能 3"},
    {"聚变机炮", "Weapon", "主要攻击模式"},
    {"微型飞弹", "Ability", "技能 2"},
    {"弹射！", "PassiveAbility", ""},
    {"呼叫机甲", "UltimateAbility", "技能 3"},
    {"光枪", "Weapon", "主要攻击模式"},
    {"职责：重装", "PassiveAbility", ""},
};

// 美 (0xDD)
inline constexpr AbilityInfo kAbilities_DD[] = {
    {"暴雪", "UltimateAbility", "技能 3"},
    {"急冻", "Ability", "技能 1"},
    {"冰墙", "Ability", "技能 2"},
    {"冰霜冲击枪", "Weapon", "主要攻击模式"},
    {"冰锥", "Weapon", "辅助攻击模式"},
};

// 黑影 (0x12E)
inline constexpr AbilityInfo kAbilities_12E[] = {
    {"自动手枪", "Weapon", "主要攻击模式"},
    {"黑客入侵", "Ability", "辅助攻击模式"},
    {"病毒侵染", "Ability", "技能 1"},
    {"位移传动", "Ability", "技能 2"},
    {"电磁脉冲", "UltimateAbility", "技能 3"},
    {"相时而动", "PassiveAbility", ""},
};

// 末日铁拳 (0x12F)
inline constexpr AbilityInfo kAbilities_12F[] = {
    {"裂地重拳", "Ability", "技能 1"},
    {"悍猛格挡", "Ability", "技能 2"},
    {"火箭重拳", "Ability", "辅助攻击模式"},
    {"毁天灭地", "UltimateAbility", "技能 3"},
    {"手炮", "Weapon", "主要攻击模式"},
    {"最佳防守……", "PassiveAbility", ""},
    {"职责：重装", "PassiveAbility", ""},
};

// 安娜 (0x13B)
inline constexpr AbilityInfo kAbilities_13B[] = {
    {"麻醉镖", "Ability", "技能 1"},
    {"生物步枪", "Weapon", "主要攻击模式"},
    {"生物手雷", "Ability", "技能 2"},
    {"纳米激素", "UltimateAbility", "技能 3"},
    {"瞄准射击", "Weapon", "辅助攻击模式"},
};

// 奥丽莎 (0x13E)
inline constexpr AbilityInfo kAbilities_13E[] = {
    {"能量标枪", "Ability", "辅助攻击模式"},
    {"强固防御", "Ability", "技能 1"},
    {"标枪旋击", "Ability", "技能 2"},
    {"撼地猛刺", "UltimateAbility", "技能 3"},
    {"强化聚变驱动器", "Weapon", "主要攻击模式"},
    {"职责：重装", "PassiveAbility", ""},
};

// 布丽吉塔 (0x195)
inline constexpr AbilityInfo kAbilities_195[] = {
    {"集结号令", "UltimateAbility", "技能 3"},
    {"鼓舞士气", "PassiveAbility", ""},
    {"恢复包", "Ability", "技能 2"},
    {"流星飞锤", "Ability", "技能 1"},
    {"火箭连枷", "Weapon", "主要攻击模式"},
    {"屏障护盾", "Ability", "辅助攻击模式"},
    {"能量盾击", "Ability", "主要攻击模式"},
};

// 莫伊拉 (0x1A2)
inline constexpr AbilityInfo kAbilities_1A2[] = {
    {"生化之触", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"生化之球", "Ability", "技能 2"},
    {"消散", "Ability", "技能 1"},
    {"聚合射线", "UltimateAbility", "技能 3"},
};

// 破坏球 (0x1CA)
inline constexpr AbilityInfo kAbilities_1CA[] = {
    {"四联火炮", "Weapon", "主要攻击模式"},
    {"地雷禁区", "UltimateAbility", "技能 3"},
    {"工程抓钩", "Ability", "辅助攻击模式"},
    {"动力铁球", "Ability", "技能 1"},
    {"重力坠击", "Ability", "下蹲"},
    {"感应护盾", "Ability", "技能 2"},
    {"职责：重装", "PassiveAbility", ""},
};

// 索杰恩 (0x1EC)
inline constexpr AbilityInfo kAbilities_1EC[] = {
    {"机动滑铲", "Ability", "技能 1"},
    {"干扰弹", "Ability", "技能 2"},
    {"电磁炮", "Weapon", "主要攻击模式"},
    {"充能射击", "Weapon", "辅助攻击模式"},
    {"机体超频", "UltimateAbility", "技能 3"},
};

// 艾什 (0x200)
inline constexpr AbilityInfo kAbilities_200[] = {
    {"短筒猎枪", "Ability", "技能 1"},
    {"召唤鲍勃", "UltimateAbility", "技能 3"},
    {"延时雷管", "Ability", "技能 2"},
    {"毒蛇", "Weapon", "主要攻击模式"},
    {"瞄准射击", "Weapon", "辅助攻击模式"},
};

// 回声 (0x206)
inline constexpr AbilityInfo kAbilities_206[] = {
    {"黏性炸弹", "Ability", "辅助攻击模式"},
    {"人格复制", "UltimateAbility", "技能 3"},
    {"三角射击", "Weapon", "主要攻击模式"},
    {"飞行", "Ability", "技能 1"},
    {"聚焦光线", "Ability", "技能 2"},
    {"滑翔", "PassiveAbility", "跳跃"},
};

// 巴蒂斯特 (0x221)
inline constexpr AbilityInfo kAbilities_221[] = {
    {"愈合冲击", "Ability", "技能 1"},
    {"维生力场", "Ability", "技能 2"},
    {"增幅矩阵", "UltimateAbility", "技能 3"},
    {"生化榴弹枪", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
    {"动力战靴", "PassiveAbility", "下蹲"},
};

// 雾子 (0x231)
inline constexpr AbilityInfo kAbilities_231[] = {
    {"狐", "UltimateAbility", "技能 3"},
    {"符", "Weapon", "主要攻击模式"},
    {"锥", "Weapon", "辅助攻击模式"},
    {"瞬", "Ability", "技能 1"},
    {"铃", "Ability", "技能 2"},
    {"攀", "PassiveAbility", "跳跃"},
};

// 渣客女王 (0x236)
inline constexpr AbilityInfo kAbilities_236[] = {
    {"锯齿利刃（格雷西）", "Ability", "辅助攻击模式"},
    {"命令怒吼", "Ability", "技能 1"},
    {"散弹枪", "Weapon", "主要攻击模式"},
    {"血斩", "Ability", "技能 2"},
    {"轰翻天", "UltimateAbility", "技能 3"},
    {"狂血奔涌", "PassiveAbility", ""},
    {"职责：重装", "PassiveAbility", ""},
};

// 西格玛 (0x23B)
inline constexpr AbilityInfo kAbilities_23B[] = {
    {"动能俘获", "Ability", "技能 1"},
    {"质量吸附", "Ability", "技能 2"},
    {"引力乱流", "UltimateAbility", "技能 3"},
    {"超能之球", "Weapon", "主要攻击模式"},
    {"实验屏障", "Ability", "辅助攻击模式"},
    {"职责：重装", "PassiveAbility", ""},
};

// 拉玛刹 (0x28D)
inline constexpr AbilityInfo kAbilities_28D[] = {
    {"虚空加速器（智械形态）", "Weapon", "主要攻击模式"},
    {"猛拳（天罚形态）", "Weapon", "主要攻击模式"},
    {"虚空屏障（智械形态）", "Ability", "辅助攻击模式"},
    {"天罚形态", "Ability", "技能 1"},
    {"铁臂（天罚形态）", "Ability", "辅助攻击模式"},
    {"吞噬漩涡", "Ability", "技能 2"},
    {"诛", "UltimateAbility", "技能 3"},
    {"职责：重装", "PassiveAbility", ""},
};

// 生命之梭 (0x291)
inline constexpr AbilityInfo kAbilities_291[] = {
    {"愈疗灵花", "Weapon", "主要攻击模式"},
    {"棘刺箭雨", "Weapon", "辅助攻击模式"},
    {"花瓣平台", "Ability", "技能 1"},
    {"回春疾行", "Ability", "跳跃"},
    {"生命之握", "Ability", "技能 2"},
    {"生命之树", "UltimateAbility", "技能 3"},
};

// 毛加 (0x30A)
inline constexpr AbilityInfo kAbilities_30A[] = {
    {"蛮力冲撞", "Ability", "技能 1"},
    {"心脏过载", "Ability", "技能 2"},
    {"笼中斗", "UltimateAbility", "技能 3"},
    {"燃火链式机枪（老枪）", "Weapon", "主要攻击模式"},
    {"爆烈链式机枪（恰恰）", "Weapon", "辅助攻击模式"},
    {"狂战士", "PassiveAbility", ""},
    {"职责：重装", "PassiveAbility", ""},
};

// 伊拉锐 (0x31C)
inline constexpr AbilityInfo kAbilities_31C[] = {
    {"烈日冲击", "Ability", "技能 1"},
    {"治疗光塔", "Ability", "技能 2"},
    {"桎梏灼日", "UltimateAbility", "技能 3"},
    {"阳焰步枪", "Weapon", "主要攻击模式"},
    {"辅助攻击模式", "Weapon", "辅助攻击模式"},
};

// 弗蕾娅 (0x32A)
inline constexpr AbilityInfo kAbilities_32A[] = {
    {"速射弩", "Weapon", "主要攻击模式"},
    {"瞄准射击", "Weapon", "辅助攻击模式"},
    {"疾冲", "Ability", "技能 1"},
    {"上升气流", "Ability", "技能 2"},
    {"流星索", "UltimateAbility", "技能 3"},
    {"赏金狩猎", "PassiveAbility", ""},
};

// 探奇 (0x32B)
inline constexpr AbilityInfo kAbilities_32B[] = {
    {"智能挖掘钻", "Weapon", "主要攻击模式"},
    {"钻地", "Ability", "技能 1"},
    {"钻头突刺", "Ability", "辅助攻击模式"},
    {"地壳震击", "UltimateAbility", "技能 3"},
    {"猛钻", "PassiveAbility", "快速近身攻击"},
    {"探险家的决心", "PassiveAbility", ""},
};

// 骇灾 (0x362)
inline constexpr AbilityInfo kAbilities_362[] = {
    {"千针雨", "UltimateAbility", "技能 3"},
    {"骨刺", "Weapon", "主要攻击模式"},
    {"尖刺护体", "Ability", "辅助攻击模式"},
    {"狂跃", "Ability", "技能 1"},
    {"尖刺墙", "Ability", "技能 2"},
    {"翻越", "PassiveAbility", "跳跃"},
    {"职责：重装", "PassiveAbility", ""},
};

// 朱诺 (0x365)
inline constexpr AbilityInfo kAbilities_365[] = {
    {"医疗冲击枪", "Weapon", "主要攻击模式"},
    {"脉冲星飞雷", "Ability", "辅助攻击模式"},
    {"滑翔推进", "Ability", "技能 1"},
    {"超能环域", "Ability", "技能 2"},
    {"轨道射线", "UltimateAbility", "技能 3"},
    {"火星套靴", "PassiveAbility", "跳跃"},
};

// 无漾 (0x3C3)
inline constexpr AbilityInfo kAbilities_3C3[] = {
    {"玄武杖", "Weapon", "主要攻击模式"},
    {"翻江浪", "Ability", "技能 2"},
    {"飞流步", "Ability", "技能 1"},
    {"养神泉", "Weapon", "辅助攻击模式"},
    {"惊涛破", "UltimateAbility", "技能 3"},
};

// 斩仇 (0x472)
inline constexpr AbilityInfo kAbilities_472[] = {
    {"旋风疾步", "Ability", "技能 1"},
    {"飞空斩击", "Ability", "技能 2"},
    {"帕拉蒂尼之牙", "Weapon", "主要攻击模式"},
    {"招架姿态", "Weapon", "辅助攻击模式"},
    {"锋锐剑气", "Ability", "主要攻击模式"},
    {"斩地巨剑", "UltimateAbility", "技能 3"},
    {"越战越勇", "PassiveAbility", ""},
};

// 金驭 (0x4C4)
inline constexpr AbilityInfo kAbilities_4C4[] = {
    {"光子马格南", "Weapon", "主要攻击模式"},
    {"屏障阵列", "Ability", "辅助攻击模式"},
    {"音速斥力场", "Ability", "技能 1"},
    {"爆能水晶", "Ability", "技能 2"},
    {"全景牢笼", "UltimateAbility", "技能 3"},
    {"护盾重构", "PassiveAbility", ""},
    {"职责：重装", "PassiveAbility", ""},
};

// 埃姆雷 (0x4D8)
inline constexpr AbilityInfo kAbilities_4D8[] = {
    {"合成连发步枪", "Weapon", "主要攻击模式"},
    {"瞄准射击", "Weapon", "辅助攻击模式"},
    {"虹吸冲击枪", "Ability", "技能 1"},
    {"赛博手雷", "Ability", "技能 2"},
    {"覆盖协议", "UltimateAbility", "技能 3"},
    {"机变体征", "PassiveAbility", ""},
};

// 安燃 (0x4DD)
inline constexpr AbilityInfo kAbilities_4DD[] = {
    {"朱雀扇", "Weapon", "主要攻击模式"},
    {"煽火风", "Weapon", "辅助攻击模式"},
    {"怒炎冲", "Ability", "技能 1"},
    {"熠闪舞", "Ability", "技能 2"},
    {"朱羽焚", "UltimateAbility", "技能 3"},
    {"朱魂返", "UltimateAbility", "技能 3"},
    {"焚身焰", "PassiveAbility", ""},
};

// 瑞稀 (0x4E3)
inline constexpr AbilityInfo kAbilities_4E3[] = {
    {"御魂镰刃", "Weapon", "主要攻击模式"},
    {"疗魂斗笠", "Ability", "辅助攻击模式"},
    {"缚魂锁链", "Ability", "技能 2"},
    {"替魂纸人", "Ability", "技能 1"},
    {"护魂结界", "UltimateAbility", "技能 3"},
    {"安魂灵气", "PassiveAbility", ""},
};

// 飞天猫 (0x516)
inline constexpr AbilityInfo kAbilities_516[] = {
    {"生物猫爪弹", "Weapon", ""},
    {"咻咻飞", "Ability", "辅助攻击模式"},
    {"救生索", "Ability", "技能 1"},
    {"呼噜噜", "Ability", "技能 2"},
    {"猫猫劫", "UltimateAbility", "技能 3"},
    {"喷气背包", "PassiveAbility", ""},
};

} // namespace gen
} // namespace ow_v2
