// ============================================================================
// AUTO-GENERATED by scripts/generate_sdk_v2.py
// DO NOT EDIT BY HAND. Source of truth:
//   - blueprint_editor/output/var_dictionary.json (statescript var names)
//   - output/dump_json/heroes.json + loadouts.json (CASC dump)
// Regenerate: python3 scripts/generate_sdk_v2.py
// ============================================================================
#pragma once

#include <cstdint>
#include <cstddef>

// weapondump.hpp — Per-(hero, graph, node) weapon ballistic data (from abilities.json)
// 131 WeaponVolley entries across 41 heroes
//
// Numeric fields: -1 means dynamic/bound at runtime (driven by a state var).
// Projectile entity is resolved to a name via abilities.json + entity_origins.json.

namespace ow {
namespace sdk {

enum class BallisticType : std::uint8_t {
    HitScan = 0,
    Projectile = 1,
    Beam = 2,
    Melee = 3,
    Unknown = 4,
};

struct WeaponEntry {
    uint32_t      hero_id;
    const char*   hero_name;
    uint32_t      graph_index;       // owning graph slot
    int16_t       slot_index;        // position in hero's graph list (proxy for keybind)
    uint16_t      node_index;        // node index inside the graph
    BallisticType ballistic;
    int           projectile_speed;   // m/s, -1 = dynamic
    int           projectile_lifetime;// -1 = dynamic
    int           pellets;
    int           fire_rate;
    uint32_t      projectile_entity_id;   // 0 if none
    const char*   projectile_entity_name; // resolved via abilities + origins; "" if unknown
};

inline constexpr WeaponEntry kWeapons[] = {
    {0x2u, "死神", 0x44u, 8, 141u, BallisticType::Projectile, -1, -1, 3, 16, 0x1320u, "死神_死亡绽放_Projectile"},
    {0x2u, "死神", 0x5D64u, 13, 618u, BallisticType::Projectile, -1, -1, -1, 12, 0x4Au, "死神_恐怖扳机_Projectile"},
    {0x3u, "猎空", 0x34u, 3, 21u, BallisticType::Projectile, -1, -1, 1, 1, 0x45u, "猎空_脉冲炸弹_Projectile"},
    {0x3u, "猎空", 0x34u, 3, 414u, BallisticType::Projectile, -1, -1, 1, 1, 0x45u, "猎空_脉冲炸弹_Projectile"},
    {0x5u, "半藏", 0x101u, 7, 328u, BallisticType::Projectile, -1, 20, 1, 2, 0x34Fu, "半藏_竜_Projectile"},
    {0x5u, "半藏", 0x101u, 7, 421u, BallisticType::Projectile, -1, 20, 1, 2, 0x34Fu, "半藏_竜_Projectile"},
    {0x6u, "托比昂", 0x16C5u, 5, 465u, BallisticType::Projectile, -1, 60, 1, 1, 0x2931u, "托比昂_部署炮台_Projectile"},
    {0x6u, "托比昂", 0x16DAu, 6, 382u, BallisticType::Projectile, -1, 10, 1, 6, 0x2902u, "托比昂_熔火核心_Projectile"},
    {0x7u, "莱因哈特", 0xE2u, 7, 130u, BallisticType::Projectile, -1, 100, 1, 1, 0x0u, ""},
    {0x8u, "法老之鹰", 0x25u, 6, 337u, BallisticType::Projectile, 45, 5, 4, 30, 0x52u, "法老之鹰_火箭弹幕_Projectile"},
    {0x8u, "法老之鹰", 0x27u, 7, 268u, BallisticType::Projectile, 7, 999, -1, 1, 0x470Du, "法老之鹰_推进背包_Projectile"},
    {0x8u, "法老之鹰", 0x2Bu, 8, 21u, BallisticType::Projectile, 45, 5, 1, -1, 0x0u, ""},
    {0x8u, "法老之鹰", 0x2Bu, 8, 277u, BallisticType::Projectile, 80, 5, 1, 5, 0x410Cu, "法老之鹰_火箭弹幕_Projectile"},
    {0x8u, "法老之鹰", 0x74u, 5, 306u, BallisticType::Projectile, 60, 5, 1, 1, 0x4746u, "法老之鹰_slot5_Projectile"},
    {0x8u, "法老之鹰", 0x7Bu, 9, 52u, BallisticType::Projectile, 60, 5, 1, 1, 0x10Fu, "法老之鹰_震荡冲击_Projectile"},
    {0x8u, "法老之鹰", 0x7Bu, 9, 206u, BallisticType::Projectile, 60, 5, 1, 1, 0x481Fu, "法老之鹰_震荡冲击_Projectile"},
    {0x8u, "法老之鹰", 0x7Bu, 9, 289u, BallisticType::Projectile, 60, 5, 1, 1, 0x6520u, "法老之鹰_震荡冲击_Projectile"},
    {0x8u, "法老之鹰", 0x7Bu, 9, 297u, BallisticType::Projectile, 60, 5, 1, 1, 0x10Fu, "法老之鹰_震荡冲击_Projectile"},
    {0x8u, "法老之鹰", 0x7Bu, 9, 356u, BallisticType::Projectile, 60, 5, 1, 1, 0x10Fu, "法老之鹰_震荡冲击_Projectile"},
    {0x8u, "法老之鹰", 0x51E9u, 11, 691u, BallisticType::Projectile, 40, 10, 2, 5, 0x52u, "法老之鹰_火箭弹幕_Projectile"},
    {0xAu, "黑百合", 0x56u, 3, 21u, BallisticType::Projectile, -1, 10, 1, 1, 0xAFu, "黑百合_剧毒诡雷_Projectile"},
    {0xAu, "黑百合", 0x56u, 3, 186u, BallisticType::Projectile, -1, 10, 1, 1, 0xAFu, "黑百合_剧毒诡雷_Projectile"},
    {0x15u, "堡垒", 0x13Au, 4, 162u, BallisticType::Projectile, -1, -1, 1, -1, 0x207u, "堡垒_强攻模式_Projectile"},
    {0x15u, "堡垒", 0x13Au, 4, 323u, BallisticType::Projectile, 100, 5, 1, 1, 0x3CEu, "堡垒_强攻模式_Projectile"},
    {0x15u, "堡垒", 0x23Bu, 6, 639u, BallisticType::Projectile, 80, 0, -1, -1, 0x3EFDu, "堡垒_火炮模式_Projectile"},
    {0x15u, "堡垒", 0x23Bu, 6, 732u, BallisticType::Projectile, 60, 0, -1, -1, 0x3EFDu, "堡垒_火炮模式_Projectile"},
    {0x15u, "堡垒", 0x3045u, 7, 148u, BallisticType::Projectile, -1, 60, 1, 2, 0x3F69u, "堡垒_A-36战术榴弹_Projectile"},
    {0x16u, "秩序之光", 0x157Eu, 5, 379u, BallisticType::Unknown, -1, 20, -1, -1, 0x0u, ""},
    {0x29u, "源氏", 0x3A3u, 7, 631u, BallisticType::Projectile, 40, 5, 1, -1, 0x7CAu, "源氏_闪_Projectile"},
    {0x29u, "源氏", 0x3A3u, 7, 640u, BallisticType::Projectile, 40, 5, 1, -1, 0x0u, ""},
    {0x40u, "路霸", 0x1F1u, 6, 194u, BallisticType::Projectile, 5, 15, 1, 4, 0x44F0u, "路霸_slot6_Projectile"},
    {0x40u, "路霸", 0x240u, 8, 426u, BallisticType::Projectile, -1, 30, 1, 1, 0x4503u, "路霸_呼吸器_Projectile"},
    {0x42u, "卡西迪", 0x1E9u, 6, 112u, BallisticType::Projectile, 30, 5, 1, 1, 0x37Du, "卡西迪_闪光弹_Projectile"},
    {0x42u, "卡西迪", 0x1E9u, 6, 203u, BallisticType::Projectile, 25, 5, 1, 1, 0x65F2u, "卡西迪_闪光弹_Projectile"},
    {0x42u, "卡西迪", 0x1E9u, 6, 208u, BallisticType::Projectile, 25, 1, 1, 1, 0x6D81u, "卡西迪_闪光弹_Projectile"},
    {0x65u, "狂鼠", 0x22Au, 3, 10u, BallisticType::Projectile, -1, -1, 1, 50, 0x515u, "狂鼠_临别礼物_Projectile"},
    {0x65u, "狂鼠", 0x22Au, 3, 36u, BallisticType::Projectile, -1, -1, 1, 50, 0x515u, "狂鼠_临别礼物_Projectile"},
    {0x65u, "狂鼠", 0x22Au, 3, 39u, BallisticType::Projectile, -1, -1, 1, 50, 0x515u, "狂鼠_临别礼物_Projectile"},
    {0x65u, "狂鼠", 0x22Au, 3, 40u, BallisticType::Projectile, -1, -1, 1, 50, 0x515u, "狂鼠_临别礼物_Projectile"},
    {0x65u, "狂鼠", 0x22Au, 3, 41u, BallisticType::Projectile, -1, -1, 1, 50, 0x515u, "狂鼠_临别礼物_Projectile"},
    {0x65u, "狂鼠", 0x22Au, 3, 42u, BallisticType::Projectile, -1, -1, 1, 50, 0x515u, "狂鼠_临别礼物_Projectile"},
    {0x65u, "狂鼠", 0x22Au, 3, 150u, BallisticType::Projectile, 5, 15, 1, 1, 0x28B9u, "狂鼠_临别礼物_Projectile"},
    {0x65u, "狂鼠", 0x96Au, 5, 227u, BallisticType::Projectile, -1, 999, 1, 1, 0xF9Bu, "狂鼠_震荡地雷_Projectile"},
    {0x65u, "狂鼠", 0x96Au, 5, 452u, BallisticType::Projectile, -1, 999, 1, 1, 0xF9Bu, "狂鼠_震荡地雷_Projectile"},
    {0x65u, "狂鼠", 0x9BAu, 6, 445u, BallisticType::Projectile, -1, 5, 1, 1, 0x11A9u, "狂鼠_捕兽夹_Projectile"},
    {0x65u, "狂鼠", 0x51E8u, 10, 476u, BallisticType::Projectile, -1, -1, 1, -1, 0x515u, "狂鼠_临别礼物_Projectile"},
    {0x68u, "查莉娅", 0x25Fu, 5, 21u, BallisticType::Projectile, -1, 60, 1, 1, 0x8CEu, "查莉娅_重力喷涌_Projectile"},
    {0x68u, "查莉娅", 0x25Fu, 5, 183u, BallisticType::Projectile, 6, 6, 1, 1, 0x47F1u, "查莉娅_重力喷涌_Projectile"},
    {0x68u, "查莉娅", 0x25Fu, 5, 284u, BallisticType::Projectile, -1, 60, 1, 1, 0x8CEu, "查莉娅_重力喷涌_Projectile"},
    {0x6Eu, "士兵：76", 0x257u, 6, 11u, BallisticType::Projectile, 50, 10, 1, 1, 0x72Du, "士兵：76_生物力场_Projectile"},
    {0x6Eu, "士兵：76", 0x257u, 6, 165u, BallisticType::Projectile, 50, 10, 1, 1, 0x72Du, "士兵：76_生物力场_Projectile"},
    {0x6Eu, "士兵：76", 0x257u, 6, 172u, BallisticType::Projectile, 24, 10, 1, 1, 0x72Du, "士兵：76_生物力场_Projectile"},
    {0x79u, "卢西奥", 0x263u, 4, 521u, BallisticType::Projectile, -1, 12, 1, 1, 0x431Fu, "卢西奥_slot4_Projectile"},
    {0xDDu, "美", 0x5FEu, 3, 620u, BallisticType::Projectile, 30, 5, 1, -1, 0x172Fu, "美_急冻_Projectile"},
    {0xDDu, "美", 0x64Au, 5, 139u, BallisticType::Projectile, -1, 60, 1, 1, 0x946u, "美_暴雪_Projectile"},
    {0xDDu, "美", 0xB48u, 6, 202u, BallisticType::Projectile, 5, 3, 1, 1, 0x4C85u, "美_暴雪_Projectile"},
    {0x12Eu, "黑影", 0xC19u, 5, 89u, BallisticType::Projectile, 72, 15, 1, 1, 0x1575u, "黑影_位移传动_Projectile"},
    {0x12Eu, "黑影", 0x4389u, 9, 1523u, BallisticType::Projectile, 50, 25, 1, 1, 0x50FEu, "黑影_病毒侵染_Projectile"},
    {0x13Bu, "安娜", 0xB97u, 4, 21u, BallisticType::Projectile, -1, 60, 1, 1, 0x1426u, "安娜_生物手雷_Projectile"},
    {0x13Bu, "安娜", 0xB9Eu, 5, 93u, BallisticType::Projectile, -1, -1, 1, 1, 0x15E9u, "安娜_纳米激素_Projectile"},
    {0x13Bu, "安娜", 0xBDDu, 6, 108u, BallisticType::Projectile, -1, 20, -1, -1, 0x15E8u, "安娜_麻醉镖_Projectile"},
    {0x13Bu, "安娜", 0xBDDu, 6, 202u, BallisticType::Projectile, -1, 0, -1, -1, 0x15E8u, "安娜_麻醉镖_Projectile"},
    {0x13Bu, "安娜", 0xBDDu, 6, 261u, BallisticType::Projectile, -1, 20, -1, -1, 0x15E8u, "安娜_麻醉镖_Projectile"},
    {0x13Bu, "安娜", 0xBDDu, 6, 288u, BallisticType::Projectile, -1, 0, -1, -1, 0x15E8u, "安娜_麻醉镖_Projectile"},
    {0x13Eu, "奥丽莎", 0x35EEu, 4, 1086u, BallisticType::Projectile, 25, 30, 1, 1, 0x1846u, "奥丽莎_标枪旋击_Projectile"},
    {0x13Eu, "奥丽莎", 0x35F1u, 5, 241u, BallisticType::Projectile, -1, 15, 1, 1, 0x4147u, "奥丽莎_能量标枪_Projectile"},
    {0x195u, "布丽吉塔", 0xEE3u, 4, 985u, BallisticType::Projectile, 30, 5, 1, 1, 0x6A33u, "布丽吉塔_屏障护盾_Projectile"},
    {0x1A2u, "莫伊拉", 0x10E4u, 6, 165u, BallisticType::Projectile, 20, -1, -1, 999, 0x0u, ""},
    {0x1A2u, "莫伊拉", 0x10E4u, 6, 540u, BallisticType::Projectile, 20, -1, -1, 999, 0x0u, ""},
    {0x1A2u, "莫伊拉", 0x10E4u, 6, 604u, BallisticType::Projectile, 20, -1, 1, 999, 0x1E61u, "莫伊拉_生化之球_Projectile"},
    {0x1A2u, "莫伊拉", 0x10E4u, 6, 707u, BallisticType::Projectile, 20, -1, 1, 999, 0x0u, ""},
    {0x1A2u, "莫伊拉", 0x10E4u, 6, 712u, BallisticType::Projectile, 20, -1, 1, 999, 0x0u, ""},
    {0x1CAu, "破坏球", 0x1517u, 8, 271u, BallisticType::Projectile, -1, 999, -1, -1, 0x2578u, "破坏球_地雷禁区_Projectile"},
    {0x1CAu, "破坏球", 0x1517u, 8, 338u, BallisticType::Projectile, -1, 999, -1, -1, 0x2578u, "破坏球_地雷禁区_Projectile"},
    {0x1CAu, "破坏球", 0x1517u, 8, 367u, BallisticType::Projectile, -1, 999, -1, -1, 0x2578u, "破坏球_地雷禁区_Projectile"},
    {0x1CAu, "破坏球", 0x1517u, 8, 455u, BallisticType::Projectile, -1, 999, 6, -1, 0x6ED5u, "破坏球_地雷禁区_Projectile"},
    {0x1CAu, "破坏球", 0x1517u, 8, 456u, BallisticType::Projectile, -1, 999, 1, -1, 0x6ED5u, "破坏球_地雷禁区_Projectile"},
    {0x1ECu, "索杰恩", 0x1441u, 6, 105u, BallisticType::Projectile, -1, 1, 1, 1, 0x31EFu, "索杰恩_机动滑铲_Projectile"},
    {0x1ECu, "索杰恩", 0x1441u, 6, 133u, BallisticType::Projectile, -1, 1, 1, 1, 0x31EFu, "索杰恩_机动滑铲_Projectile"},
    {0x1ECu, "索杰恩", 0x1441u, 6, 353u, BallisticType::Projectile, -1, 10, 1, 1, 0x31EFu, "索杰恩_机动滑铲_Projectile"},
    {0x1ECu, "索杰恩", 0x1441u, 6, 365u, BallisticType::Projectile, -1, 1, 1, 1, 0x31EFu, "索杰恩_机动滑铲_Projectile"},
    {0x1ECu, "索杰恩", 0x1E6Fu, 5, 1062u, BallisticType::Projectile, 0, 0, 1, 1, 0x31EFu, "索杰恩_机动滑铲_Projectile"},
    {0x1ECu, "索杰恩", 0x1E6Fu, 5, 1070u, BallisticType::Projectile, 0, 0, 1, 1, 0x31EFu, "索杰恩_机动滑铲_Projectile"},
    {0x200u, "艾什", 0x14FDu, 2, 103u, BallisticType::Projectile, -1, 30, 1, 1, 0x2533u, "艾什_延时雷管_Projectile"},
    {0x200u, "艾什", 0x1513u, 5, 169u, BallisticType::Projectile, -1, -1, -1, -1, 0x2B61u, "艾什_短筒猎枪_Projectile"},
    {0x200u, "艾什", 0x1513u, 5, 223u, BallisticType::Projectile, -1, -1, 15, -1, 0x2B61u, "艾什_短筒猎枪_Projectile"},
    {0x200u, "艾什", 0x1536u, 6, 220u, BallisticType::Projectile, 7, 10, 5, 1, 0x43C0u, "艾什_召唤鲍勃_Projectile"},
    {0x206u, "回声", 0x1C36u, 6, 927u, BallisticType::Projectile, 50, 100, 1, -1, 0x2CBAu, "回声_黏性炸弹_Projectile"},
    {0x221u, "巴蒂斯特", 0x1761u, 4, 115u, BallisticType::Projectile, -1, 60, 1, 1, 0x29A8u, "巴蒂斯特_slot4_Projectile"},
    {0x221u, "巴蒂斯特", 0x51F1u, 9, 417u, BallisticType::Projectile, 250, 10, 1, 1, 0x4014u, "巴蒂斯特_生化榴弹枪_Projectile"},
    {0x221u, "巴蒂斯特", 0x51F1u, 9, 418u, BallisticType::Projectile, -1, -1, 1, 1, 0x4013u, "巴蒂斯特_生化榴弹枪_Projectile"},
    {0x231u, "雾子", 0x30D8u, 6, 71u, BallisticType::Projectile, -1, 30, 1, 1, 0x3FD3u, "雾子_铃_Projectile"},
    {0x231u, "雾子", 0x5163u, 10, 392u, BallisticType::Projectile, -1, 10, 1, -1, 0x6606u, "雾子_slot10_Projectile"},
    {0x231u, "雾子", 0x5163u, 10, 423u, BallisticType::Projectile, -1, 10, 1, -1, 0x6606u, "雾子_slot10_Projectile"},
    {0x236u, "渣客女王", 0x215Fu, 6, 697u, BallisticType::Projectile, -1, -1, -1, -1, 0x3555u, "渣客女王_锯齿利刃（格雷西）_Projectile"},
    {0x236u, "渣客女王", 0x215Fu, 6, 1095u, BallisticType::Projectile, -1, -1, -1, -1, 0x3555u, "渣客女王_锯齿利刃（格雷西）_Projectile"},
    {0x236u, "渣客女王", 0x2209u, 5, 987u, BallisticType::Projectile, -1, 0, -1, -1, 0x458Cu, "渣客女王_血斩_Projectile"},
    {0x23Bu, "西格玛", 0x1BBBu, 6, 566u, BallisticType::Projectile, -1, 30, -1, -1, 0x18B7u, "西格玛_质量吸附_Projectile"},
    {0x23Bu, "西格玛", 0x1BBBu, 6, 786u, BallisticType::Projectile, -1, 30, -1, -1, 0x18B7u, "西格玛_质量吸附_Projectile"},
    {0x23Bu, "西格玛", 0x1BBBu, 6, 809u, BallisticType::Projectile, -1, 30, -1, -1, 0x18B7u, "西格玛_质量吸附_Projectile"},
    {0x23Bu, "西格玛", 0x1BBBu, 6, 812u, BallisticType::Projectile, -1, 30, -1, -1, 0x18B7u, "西格玛_质量吸附_Projectile"},
    {0x23Bu, "西格玛", 0x1D02u, 5, 581u, BallisticType::Projectile, 150, 5, -1, 999, 0x2CBAu, "回声_黏性炸弹_Projectile"},
    {0x28Du, "拉玛刹", 0x2948u, 7, 802u, BallisticType::Projectile, -1, 60, -1, 1, 0x3523u, "拉玛刹_吞噬漩涡_Projectile"},
    {0x28Du, "拉玛刹", 0x2948u, 7, 1074u, BallisticType::Projectile, -1, 60, -1, 1, 0x3523u, "拉玛刹_吞噬漩涡_Projectile"},
    {0x28Du, "拉玛刹", 0x51DEu, 10, 349u, BallisticType::Projectile, 80, 5, 6, 1, 0x663Fu, "拉玛刹_slot10_Projectile"},
    {0x291u, "生命之梭", 0x2219u, 4, 371u, BallisticType::Projectile, -1, 20, 1, 1, 0x450Fu, "生命之梭_花瓣平台_Projectile"},
    {0x291u, "生命之梭", 0x51F4u, 10, 350u, BallisticType::Projectile, 8, 10, 1, 1, 0x4809u, "生命之梭_slot10_Projectile"},
    {0x291u, "生命之梭", 0x51F4u, 10, 514u, BallisticType::Projectile, 25, 20, 1, 1, 0x6F4Cu, "生命之梭_slot10_Projectile"},
    {0x31Cu, "伊拉锐", 0x3CABu, 6, 755u, BallisticType::Projectile, 30, 10, 1, 1, 0x4AC0u, "伊拉锐_桎梏灼日_Projectile"},
    {0x31Cu, "伊拉锐", 0x3DF4u, 3, 115u, BallisticType::Projectile, -1, 20, 1, 1, 0x4B4Au, "伊拉锐_治疗光塔_Projectile"},
    {0x32Au, "弗蕾娅", 0x4F14u, 7, 728u, BallisticType::Projectile, 70, 5, 1, 25, 0x5E3Du, "弗蕾娅_流星索_Projectile"},
    {0x32Bu, "探奇", 0x4587u, 3, 352u, BallisticType::Projectile, -1, -1, 1, 15, 0x5AFFu, "探奇_猛钻_Projectile"},
    {0x362u, "骇灾", 0x43BFu, 4, 1290u, BallisticType::Projectile, -1, 0, 1, -1, 0x50BCu, "骇灾_尖刺护体_Projectile"},
    {0x362u, "骇灾", 0x4A72u, 8, 979u, BallisticType::Projectile, -1, -1, 1, 1, 0x6195u, "骇灾_千针雨_Projectile"},
    {0x362u, "骇灾", 0x4BCFu, 6, 685u, BallisticType::Projectile, 60, 10, 1, 1, 0x5986u, "骇灾_尖刺墙_Projectile"},
    {0x365u, "朱诺", 0x4695u, 6, 778u, BallisticType::Unknown, -1, 50, 1, 999, 0x0u, ""},
    {0x365u, "朱诺", 0x4695u, 6, 815u, BallisticType::Projectile, -1, 5, 1, 999, 0x534Fu, "朱诺_脉冲星飞雷_Projectile"},
    {0x365u, "朱诺", 0x4857u, 8, 802u, BallisticType::Projectile, -1, 30, 1, 1, 0x5530u, "朱诺_超能环域_Projectile"},
    {0x365u, "朱诺", 0x4857u, 8, 1180u, BallisticType::Projectile, -1, -1, 1, 1, 0x5BAEu, "朱诺_超能环域_Projectile"},
    {0x365u, "朱诺", 0x4857u, 8, 1182u, BallisticType::Projectile, -1, -1, 1, 1, 0x5BAEu, "朱诺_超能环域_Projectile"},
    {0x365u, "朱诺", 0x4857u, 8, 1183u, BallisticType::Projectile, -1, -1, 1, 1, 0x5BAEu, "朱诺_超能环域_Projectile"},
    {0x472u, "斩仇", 0x5175u, 6, 1095u, BallisticType::Projectile, -1, 3, -1, -1, 0x62A0u, "斩仇_飞空斩击_Projectile"},
    {0x472u, "斩仇", 0x5176u, 4, 1206u, BallisticType::Projectile, -1, 100, 1, 1, 0x0u, ""},
    {0x4C4u, "金驭", 0x57C4u, 10, 416u, BallisticType::Projectile, -1, 100, -1, -1, 0x6861u, "金驭_全景牢笼_Projectile"},
    {0x4C4u, "金驭", 0x5849u, 9, 108u, BallisticType::Projectile, -1, 0, -1, -1, 0x686Bu, "金驭_爆能水晶_Projectile"},
    {0x4D8u, "埃姆雷", 0x56EDu, 5, 21u, BallisticType::Projectile, -1, 60, 1, 1, 0x6909u, "埃姆雷_赛博手雷_Projectile"},
    {0x4D8u, "埃姆雷", 0x56EDu, 5, 270u, BallisticType::Projectile, -1, 60, 1, 1, 0x711Du, "埃姆雷_赛博手雷_Projectile"},
    {0x4D8u, "埃姆雷", 0x56FBu, 4, 225u, BallisticType::Projectile, -1, 10, 1, 999, 0x68EEu, "埃姆雷_虹吸冲击枪_Projectile"},
    {0x4D8u, "埃姆雷", 0x5732u, 6, 1159u, BallisticType::Projectile, -1, 5, 1, 1, 0x6AF7u, "埃姆雷_覆盖协议_Projectile"},
    {0x4D8u, "埃姆雷", 0x5732u, 6, 1235u, BallisticType::Projectile, -1, 5, 1, 1, 0x6B18u, "埃姆雷_覆盖协议_Projectile"},
    {0x4E3u, "瑞稀", 0x5A08u, 5, 346u, BallisticType::Projectile, -1, 8, 1, 1, 0x6CEFu, "瑞稀_疗魂斗笠_Projectile"},
};
inline constexpr std::size_t kWeaponCount = 131;

inline const WeaponEntry* WeaponsBegin() noexcept { return kWeapons; }
inline const WeaponEntry* WeaponsEnd()   noexcept { return kWeapons + kWeaponCount; }

inline std::size_t CountHeroWeapons(uint32_t hero_id) noexcept {
    std::size_t n = 0;
    for (const auto& w : kWeapons) if (w.hero_id == hero_id) ++n;
    return n;
}

inline const WeaponEntry* FindHeroWeaponByBallistic(uint32_t hero_id, BallisticType bt) noexcept {
    for (const auto& w : kWeapons) if (w.hero_id == hero_id && w.ballistic == bt) return &w;
    return nullptr;
}

inline bool BallisticIsDeflectable(BallisticType bt) noexcept {
    return bt == BallisticType::Projectile;
}

inline bool HeroCanBeDeflected(uint32_t hero_id) noexcept {
    return FindHeroWeaponByBallistic(hero_id, BallisticType::Projectile) != nullptr;
}

inline const char* BallisticName(BallisticType bt) noexcept {
    switch (bt) {
    case BallisticType::HitScan: return "HitScan";
    case BallisticType::Projectile: return "Projectile";
    case BallisticType::Beam: return "Beam";
    case BallisticType::Melee: return "Melee";
    case BallisticType::Unknown: return "Unknown";
    }
    return "?";
}

} // namespace sdk
} // namespace ow
