#!/usr/bin/env python3
"""Generate C++ SDK header files from CASC dump JSON data.

Usage: python3 generate_sdk.py ./dump_output/ ./sdk_output/

Reads:
  - heroes.json: hero_id → name + loadouts
  - statescript_data.json: hero → graphs → sync_vars + node bindings

Generates:
  - hero_data.hpp: hero_id enum + name mapping + ability info
  - var_data.hpp: var_id → semantic context (graph, node_type, role)
"""

import json, os, sys
from collections import defaultdict

def main():
    dump_dir = sys.argv[1] if len(sys.argv) > 1 else "./dump_output"
    out_dir = sys.argv[2] if len(sys.argv) > 2 else "./sdk_output"
    os.makedirs(out_dir, exist_ok=True)

    heroes = json.load(open(os.path.join(dump_dir, "heroes.json")))
    ss_data = json.load(open(os.path.join(dump_dir, "statescript_data.json")))

    # Build hero → graph → ability mapping
    hero_abilities = {}
    for h in heroes:
        hid = h["hero_id"]
        if not h.get("is_hero"): continue
        abilities = []
        for lo in h.get("loadouts", []):
            cat = lo["category"]
            if cat in ("HeroStats", "Subrole"): continue
            name = (lo.get("name_zhCN") or "?").strip('\0').strip()
            button = (lo.get("button") or "").strip('\0').strip()
            abilities.append({"name": name, "category": cat, "button": button, "guid": lo["guid_index"]})
        hero_abilities[hid] = {"name": (h.get("name_zhCN") or "?").strip('\0').strip(), "abilities": abilities}

    # Build var_id → context from statescript node bindings
    var_context = defaultdict(lambda: {"heroes": set(), "node_types": set(), "roles": set(), "graphs": set()})

    for h in ss_data:
        hid = h["hero_id"]
        hname = (h.get("hero_name") or "?").strip('\0').strip()
        for gi, g in enumerate(h.get("graphs", [])):
            gidx = g.get("graph_index", "?")
            for node in g.get("node_var_refs", []):
                ntype = node.get("node_type", "?")
                label = node.get("label") or ""
                for w in node.get("writes", []):
                    vid = w.get("identifier_index")
                    if vid:
                        ctx = var_context[vid]
                        ctx["heroes"].add(hid)
                        ctx["node_types"].add(ntype)
                        ctx["roles"].add(f"write@{ntype}")
                        ctx["graphs"].add(f"{hid}:G{gi}:{gidx}")
                for r in node.get("reads", []):
                    vid = r.get("identifier_index")
                    if vid:
                        ctx = var_context[vid]
                        ctx["heroes"].add(hid)
                        ctx["node_types"].add(ntype)
                        ctx["roles"].add(f"read@{ntype}")
                        ctx["graphs"].add(f"{hid}:G{gi}:{gidx}")

    # ========== Generate hero_data.hpp ==========
    with open(os.path.join(out_dir, "hero_data_gen.hpp"), "w") as f:
        f.write("// AUTO-GENERATED by generate_sdk.py from CASC dump — do not edit manually\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace ow_v2 {\nnamespace gen {\n\n")

        # Hero name mapping
        f.write("inline const char* HeroNameZhCN(uint32_t hero_id) noexcept {\n    switch (hero_id) {\n")
        for h in sorted(heroes, key=lambda x: int(x["hero_id"], 16)):
            if not h.get("is_hero"): continue
            hid = int(h["hero_id"], 16)
            name = (h.get("name_zhCN") or "?").strip('\0').strip()
            f.write(f'    case 0x{hid:X}: return "{name}";\n')
        f.write('    default: return "?";\n    }\n}\n\n')

        # Ability info per hero
        f.write("struct AbilityInfo {\n    const char* name;\n    const char* category;\n    const char* button;\n};\n\n")

        for hid, info in sorted(hero_abilities.items(), key=lambda x: int(x[0], 16)):
            hid_int = int(hid, 16)
            safe_name = info["name"].replace(" ", "").replace(".", "").replace("：", "_")
            f.write(f"// {info['name']} (0x{hid_int:X})\n")
            f.write(f"inline constexpr AbilityInfo kAbilities_{hid_int:X}[] = {{\n")
            for ab in info["abilities"]:
                f.write(f'    {{"{ab["name"]}", "{ab["category"]}", "{ab["button"]}"}},\n')
            f.write("};\n\n")

        f.write("} // namespace gen\n} // namespace ow_v2\n")

    # ========== Generate var_data.hpp ==========
    with open(os.path.join(out_dir, "var_data_gen.hpp"), "w") as f:
        f.write("// AUTO-GENERATED by generate_sdk.py from CASC dump — do not edit manually\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace ow_v2 {\nnamespace gen {\n\n")

        # Universal vars (present on 40+ heroes)
        universal = [(vid, ctx) for vid, ctx in var_context.items() if len(ctx["heroes"]) >= 40]
        f.write(f"// Universal state variables (shared by 40+ heroes): {len(universal)}\n")
        f.write("inline const char* UniversalVarContext(uint16_t var_id) noexcept {\n    switch (var_id) {\n")
        for vid, ctx in sorted(universal, key=lambda x: int(x[0], 16)):
            vid_int = int(vid, 16)
            ntypes = ",".join(sorted(ctx["node_types"]))[:60]
            f.write(f'    case 0x{vid_int:04X}: return "{ntypes}";\n')
        f.write('    default: return nullptr;\n    }\n}\n\n')

        # Var → node type role mapping (for ALL vars with known context)
        # Output as a flat table
        f.write(f"// Total vars with context: {len(var_context)}\n")
        f.write("struct VarContext {\n")
        f.write("    uint16_t var_id;\n")
        f.write("    uint8_t hero_count;\n")
        f.write("    const char* primary_node_type;  // most common node type that uses this var\n")
        f.write("    const char* role;               // write/read context\n")
        f.write("};\n\n")

        f.write(f"inline constexpr VarContext kVarContextTable[] = {{\n")
        for vid, ctx in sorted(var_context.items(), key=lambda x: -len(x[1]["heroes"])):
            vid_int = int(vid, 16)
            hcount = min(255, len(ctx["heroes"]))
            # Get most common node type
            prim = sorted(ctx["node_types"])[0] if ctx["node_types"] else "?"
            prim = prim.replace("STUStatescript", "SS_")[:30]
            role = sorted(ctx["roles"])[0] if ctx["roles"] else "?"
            role = role[:40]
            f.write(f'    {{0x{vid_int:04X}, {hcount}, "{prim}", "{role}"}},\n')
        f.write("};\n")
        f.write(f"inline constexpr int kVarContextCount = {len(var_context)};\n\n")

        f.write("} // namespace gen\n} // namespace ow_v2\n")

    # ========== Summary ==========
    print(f"Generated:")
    print(f"  {out_dir}/hero_data_gen.hpp — {len(hero_abilities)} heroes with abilities")
    print(f"  {out_dir}/var_data_gen.hpp — {len(var_context)} vars with context, {len(universal)} universal")

if __name__ == "__main__":
    main()
