// ============================================================================
// AUTO-GENERATED by scripts/generate_sdk_v2.py
// DO NOT EDIT BY HAND. Source of truth:
//   - blueprint_editor/output/var_dictionary.json (statescript var names)
//   - output/dump_json/heroes.json + loadouts.json (CASC dump)
// Regenerate: python3 scripts/generate_sdk_v2.py
// ============================================================================
#pragma once

#include <cstdint>
#include <cstddef>

// abilitydump.hpp — Loadout (ability) ID → name + slot
// 793 loadouts across 50 playable heroes
// Slot mapping: 主要攻击=LMB, 辅助攻击=RMB, 技能1=Shift, 技能2=E, 技能3=Ult, 被动=Passive

namespace ow {
namespace sdk {

/// Default keybind / slot for an ability. None = no key bound (HeroStats / Subrole).
enum class AbilitySlot : std::uint8_t {
    None = 0,
    LMB = 1,
    RMB = 2,
    Shift = 3,
    E = 4,
    Ult = 5,
    Passive = 6,
    Jump = 7,
    Crouch = 8,
    CrouchToggle = 9,
    Interact = 10,
    Melee = 11,
    Reload = 12,
    NextWeapon = 13,
    EquipWeapon1 = 14,
};

/// Loadout category from STULoadout.
enum class AbilityCategory : std::uint8_t {
    Weapon = 0,
    Ability = 1,
    UltimateAbility = 2,
    Passive = 3,
    Perk = 4,
    HeroStats = 5,
    Subrole = 6,
};

/// One ability/loadout entry.
struct Ability {
    uint32_t        loadout_id;   // STULoadout guid_index
    uint32_t        hero_id;      // owning hero (0 if loadout is shared/orphan)
    const char*     name_zhCN;    // 中文显示名
    const char*     desc_zhCN;    // 简短中文描述
    AbilityCategory category;
    AbilitySlot     slot;         // 默认按键槽
    const char*     button_raw;   // 原始 button string (e.g. "技能 1")
    bool            hidden;       // is_hidden flag from CASC
};

// 死神 (0x2) — 6 abilities
inline constexpr Ability kAbilities_2[] = {
    {0x10u, 0x2u, "死亡绽放", "对附近所有敌人造成伤害", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x13u, 0x2u, "地狱火霰弹枪", "近距离散射武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x14u, 0x2u, "暗影步", "传送至指定位置", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x11u, 0x2u, "收割", "造成伤害可治疗自己", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
    {0x12u, 0x2u, "幽灵形态", "移动更快且变为无敌状态，但无法射击", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xE82u, 0x2u, "恐怖扳机", "用两把地狱火霰弹枪打出具有远距离精准度的齐射", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
};
inline constexpr std::size_t kAbilities_2_count = 6;

// 猎空 (0x3) — 4 abilities
inline constexpr Ability kAbilities_3[] = {
    {0x1u, 0x3u, "闪现", "传送至移动方向", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x2u, 0x3u, "闪回", "回到传送前的位置并恢复至当时的生命值", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x3u, 0x3u, "脉冲炸弹", "扔出一枚威力巨大的 粘性炸弹", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x4u, 0x3u, "脉冲双枪", "近距离全自动武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
};
inline constexpr std::size_t kAbilities_3_count = 4;

// 天使 (0x4) — 9 abilities
inline constexpr Ability kAbilities_4[] = {
    {0x3Cu, 0x4u, "天使之杖", "长按可以治疗队友", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x3Bu, 0x4u, "守护天使", "飞向一名队友。在飞行时，按跳跃可以向前飞，按下蹲可以向上飞", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x3Du, 0x4u, "天使之杖", "长按可以增加队友造成的伤害", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", true},
    {0x3Au, 0x4u, "重生", "复活一名阵亡的队友", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xE7Bu, 0x4u, "快速治疗", "治疗天使之杖的激活目标，对生命值低于一半盟友的治疗量翻倍", AbilityCategory::Ability, AbilitySlot::Reload, "装填弹药", false},
    {0x3Eu, 0x4u, "天使冲击枪", "自动武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x5u, 0x4u, "天使降临", "减缓下降速度", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
    {0xE72u, 0x4u, "迅捷恢复", "快速激活生命恢复效果", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
    {0x167u, 0x4u, "女武神", "获得飞行能力并强化各技能", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
};
inline constexpr std::size_t kAbilities_4_count = 9;

// 半藏 (0x5) — 6 abilities
inline constexpr Ability kAbilities_5[] = {
    {0x8u, 0x5u, "竜", "召唤致命的天竜之魂吞噬遇到的所有敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x6u, 0x5u, "音", "击中后短时间内显示 敌人位置", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x1E5u, 0x5u, "岚", "接下来的5发箭矢可以弹射 瞬间发出但伤害降低", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xAu, 0x5u, "风", "长按鼠标左键然后放开可以射得更远", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x7u, 0x5u, "攀", "跃上并沿着墙壁攀爬", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
    {0x1D9u, 0x5u, "跃", "二段跳", AbilityCategory::Ability, AbilitySlot::Jump, "跳跃", false},
};
inline constexpr std::size_t kAbilities_5_count = 6;

// 托比昂 (0x6) — 6 abilities
inline constexpr Ability kAbilities_6[] = {
    {0x225u, 0x6u, "部署炮台", "部署一个自动建造的炮台", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x226u, 0x6u, "热力过载", "获得额外生命值，同时提高攻击、移动 及装弹速度", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x227u, 0x6u, "熔火核心", "在地上制造熔渣池，对敌人造成伤害。对护甲造成额外伤害", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x1Du, 0x6u, "铆钉枪", "慢射速的远距离武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x1Eu, 0x6u, "辅助攻击模式", "火力强大但命中率不佳的近距离武器", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", true},
    {0x229u, 0x6u, "锻造锤", "挥动锻造锤可以修理炮台或攻击敌人", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
};
inline constexpr std::size_t kAbilities_6_count = 6;

// 莱因哈特 (0x7) — 6 abilities
inline constexpr Ability kAbilities_7[] = {
    {0x28u, 0x7u, "冲锋", "向前冲锋并将一名敌人重击到墙上", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x27u, 0x7u, "裂地猛击", "击倒前方所有敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x29u, 0x7u, "烈焰打击", "射出一道炽热能量波", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x2Bu, 0x7u, "火箭重锤", "毁灭性的近战武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x2Au, 0x7u, "屏障力场", "长按 %1$s 可以展开一道正面能量屏障", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x347u, 0x7u, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_7_count = 6;

// 法老之鹰 (0x8) — 6 abilities
inline constexpr Ability kAbilities_8[] = {
    {0xBu, 0x8u, "火箭弹幕", "原地悬浮，发射一连串 致命的迷你火箭", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xCu, 0x8u, "推进背包", "快速向上飞行 补充部分燃料", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xEu, 0x8u, "震荡冲击", "射出爆炸性冲击击退敌人", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xFu, 0x8u, "火箭发射器", "远距离爆炸式弹道武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0xDu, 0x8u, "悬浮背包", "长按可以悬浮在空中 燃料消耗完后会缓慢降落 落地时才能恢复燃料", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
    {0x445u, 0x8u, "疾冲背包", "沿水平方向推进", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
};
inline constexpr std::size_t kAbilities_8_count = 6;

// 温斯顿 (0x9) — 6 abilities
inline constexpr Ability kAbilities_9[] = {
    {0x2Du, 0x9u, "喷射背包", "向前跃向空中，着陆后对附近的敌人造成伤害", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x2Cu, 0x9u, "原始暴怒", "额外获得大量生命值 但只能跳跃和拳击敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x2Eu, 0x9u, "屏障发射器", "部署一个保护性能量罩", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x2Fu, 0x9u, "特斯拉炮", "可攻击前方锥形范围的电能武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x305u, 0x9u, "辅助攻击模式", "长按充能，松开后射出集束电击", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x347u, 0x9u, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_9_count = 6;

// 黑百合 (0xA) — 5 abilities
inline constexpr Ability kAbilities_A[] = {
    {0x24u, 0xAu, "抓钩", "射出抓钩并把自己拉向目标位置", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x22u, 0xAu, "红外侦测", "为队友提供敌方位置情报", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x23u, 0xAu, "剧毒诡雷", "射出一个剧毒陷阱", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x26u, 0xAu, "黑百合之吻", "全自动突击武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x25u, 0xAu, "瞄准射击", "长按可以进行远距离狙击", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
};
inline constexpr std::size_t kAbilities_A_count = 5;

// 堡垒 (0x15) — 6 abilities
inline constexpr Ability kAbilities_15[] = {
    {0x303u, 0x15u, "A-36战术榴弹", "发射一枚炸弹，能在墙壁间反弹 并在击中敌人或地面时爆炸", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x16u, 0x15u, "切换模式", "切换不同的作战模式", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x18u, 0x15u, "侦察模式", "配有轻型高精度武器的机动模式", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x19u, 0x15u, "强攻模式", "配有大火力轮转机枪的慢速 坦克模式", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x15u, 0x15u, "火炮模式", "进入固定状态，发射最多3枚火力强大的炮弹", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x118u, 0x15u, "抗击装甲", "降低切换模式后受到的伤害", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_15_count = 6;

// 秩序之光 (0x16) — 5 abilities
inline constexpr Ability kAbilities_16[] = {
    {0x38u, 0x16u, "光子发射器", "威力逐渐增强的近距离光束武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x39u, 0x16u, "辅助攻击模式", "长按充能，松开后射出会爆炸的能量球", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x36u, 0x16u, "哨戒炮", "部署一个小型炮台对敌人造成伤害并使其减速", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xFDu, 0x16u, "光子屏障", "部署一个大型能量屏障", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x35u, 0x16u, "传送面板", "制造两个临时传送面板，可以在它们之间进行瞬间传送", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
};
inline constexpr std::size_t kAbilities_16_count = 5;

// 禅雅塔 (0x20) — 6 abilities
inline constexpr Ability kAbilities_20[] = {
    {0x34u, 0x20u, "灭", "弹道能量武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x33u, 0x20u, "辅助攻击模式", "蓄力后可以射出一连串法球", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x32u, 0x20u, "乱", "将纷乱法球射向一个敌人可以增加其受到的伤害", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x31u, 0x20u, "谐", "将和谐法球射向盟友可以为其恢复生命值", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x30u, 0x20u, "圣", "变为无敌状态，加速 并治疗附近的盟友", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x34Du, 0x20u, "蹬", "快速近身攻击伤害提高50%% 击退效果大幅提高", AbilityCategory::Passive, AbilitySlot::Passive, "快速近身攻击", false},
};
inline constexpr std::size_t kAbilities_20_count = 6;

// 源氏 (0x29) — 6 abilities
inline constexpr Ability kAbilities_29[] = {
    {0xD8u, 0x29u, "斩", "致命的近战武器", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xD9u, 0x29u, "闪", "招架向你射来的飞弹并将其向你瞄准方向反弹回去，同时还能格挡近战攻击", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xDAu, 0x29u, "影", "快速向前冲刺，对遇到的敌人造成伤害。消灭敌人可以重置冷却时间", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xDBu, 0x29u, "镖", "扔出3发精准的手里剑", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0xDCu, 0x29u, "辅助攻击模式", "向前方弧形范围扔出3发手里剑", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xDDu, 0x29u, "灵", "可以爬墙和二段跳", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
};
inline constexpr std::size_t kAbilities_29_count = 6;

// 路霸 (0x40) — 6 abilities
inline constexpr Ability kAbilities_40[] = {
    {0x79u, 0x40u, "鸡飞狗跳", "对面前的敌人造成伤害并将他们击退", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xD54u, 0x40u, "爆裂枪", "近距离散射武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0xD55u, 0x40u, "辅助攻击模式", "发射能炸出此武器近距离主要攻击模式弹丸的中距离飞弹", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x7Du, 0x40u, "链钩", "将一个目标拉向身边", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x7Cu, 0x40u, "呼吸器", "治疗自己并降低受到的伤害", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x347u, 0x40u, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_40_count = 6;

// 卡西迪 (0x42) — 5 abilities
inline constexpr Ability kAbilities_42[] = {
    {0x61u, 0x42u, "神射手", "面对你的敌人。按下 %1$s 锁定目标 随后按下 %1$s 或 %2$s 开枪", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x5Fu, 0x42u, "战术翻滚", "向移动方向翻滚，降低所受伤害 并装填子弹", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x60u, 0x42u, "闪光弹", "限制前方的敌人 减速并禁用敌人的位移技能", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x5Du, 0x42u, "维和者", "准确致命的左轮枪", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x5Eu, 0x42u, "连射", "射光剩余的所有子弹", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
};
inline constexpr std::size_t kAbilities_42_count = 5;

// 狂鼠 (0x65) — 5 abilities
inline constexpr Ability kAbilities_65[] = {
    {0xCDu, 0x65u, "榴弹发射器", "弹跳爆炸式弹道武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0xC9u, 0x65u, "震荡地雷", "按下 %1$s 扔出一个可以击退敌人的地雷然后按下 %2$s 引爆", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xCCu, 0x65u, "捕兽夹", "放置一个可暂时使敌人失去行动能力的陷阱", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xCBu, 0x65u, "炸弹轮胎", "操控并引爆一个 会爆炸的轮胎", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xCAu, 0x65u, "临别礼物", "爆炸不会对自己造成伤害 阵亡后丢下炸弹", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_65_count = 5;

// 查莉娅 (0x68) — 7 abilities
inline constexpr Ability kAbilities_68[] = {
    {0x5Bu, 0x68u, "重力喷涌", "生成重力漩涡 将敌人拉向中心", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x59u, 0x68u, "粒子屏障", "在你周围生成 伤害吸收屏障", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x5Au, 0x68u, "投射屏障", "在盟友周围生成伤害 吸收屏障", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x57u, 0x68u, "粒子炮", "近距离线性光束武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x58u, 0x68u, "辅助攻击模式", "可以射出能量炸弹的武器", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x5Cu, 0x68u, "能量转换", "阻挡伤害可以提高粒子炮的伤害", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
    {0x347u, 0x68u, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_68_count = 7;

// 士兵：76 (0x6E) — 5 abilities
inline constexpr Ability kAbilities_6E[] = {
    {0x8Fu, 0x6Eu, "疾跑", "快速向前移动", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x90u, 0x6Eu, "生物力场", "部署一个可以治疗自己和 盟友的力场", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x8Du, 0x6Eu, "重型脉冲步枪", "全自动突击武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x8Eu, 0x6Eu, "螺旋飞弹", "射出一连串高爆飞弹", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", true},
    {0x91u, 0x6Eu, "战术目镜", "自动瞄准视野范围内的敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
};
inline constexpr std::size_t kAbilities_6E_count = 5;

// 卢西奥 (0x79) — 6 abilities
inline constexpr Ability kAbilities_79[] = {
    {0xB5u, 0x79u, "切歌", "在两种音效之间切换： 治愈音效可治疗附近盟友 加速音效可让附近盟友 更快地移动", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xA5u, 0x79u, "强音", "强化当前歌曲的效果", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xA1u, 0x79u, "音速扩音器", "超音速飞弹发射器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0xA3u, 0x79u, "音波", "射出近距离冲击波 击退敌人", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xA6u, 0x79u, "音障", "为附近盟友提供临时的额外生命值", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xA7u, 0x79u, "滑墙", "跳向墙壁并在其表面滑行", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
};
inline constexpr std::size_t kAbilities_79_count = 6;

// D.Va (0x7A) — 9 abilities
inline constexpr Ability kAbilities_7A[] = {
    {0xD0u, 0x7Au, "推进器", "向你的正前方突进", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xD1u, 0x7Au, "防御矩阵", "挡住前方射来的飞射物", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xD2u, 0x7Au, "自毁", "使机甲过载并将自己弹射出去，机甲会在短时间后爆炸", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xCFu, 0x7Au, "聚变机炮", "全自动近距离散射 武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x16Cu, 0x7Au, "微型飞弹", "射出一连串高爆飞弹", AbilityCategory::Ability, AbilitySlot::E, "技能 2", true},
    {0xDEu, 0x7Au, "弹射！", "当机甲被摧毁时 D.Va从中弹出", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
    {0xDFu, 0x7Au, "呼叫机甲", "呼叫一台全新的机甲", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xE0u, 0x7Au, "光枪", "自动武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x347u, 0x7Au, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_7A_count = 9;

// 美 (0xDD) — 5 abilities
inline constexpr Ability kAbilities_DD[] = {
    {0xD5u, 0xDDu, "暴雪", "发射一台气候控制无人机，可以冰冻大范围内的敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xD6u, 0xDDu, "急冻", "变为无敌并恢复生命值", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xD7u, 0xDDu, "冰墙", "在前方生成一堵冰墙", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xD3u, 0xDDu, "冰霜冲击枪", "可以减速敌人的近距离 范围喷射武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0xD4u, 0xDDu, "冰锥", "射出远距离冰锥", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
};
inline constexpr std::size_t kAbilities_DD_count = 5;

// 黑影 (0x12E) — 6 abilities
inline constexpr Ability kAbilities_12E[] = {
    {0xE8u, 0x12Eu, "自动手枪", "近距离自动武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0xEAu, 0x12Eu, "黑客入侵", "长按后侵入目标。被侵入的敌人无法 使用技能且隔墙可见。被侵入的急救包 刷新速度更快且无法被敌人使用 受到伤害会打断侵入…", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", true},
    {0x3D6u, 0x12Eu, "病毒侵染", "用一枚智能体侵染敌人，造成持续伤害 病毒对被侵入的敌人造成伤害更快", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xE6u, 0x12Eu, "位移传动", "扔出一个信标并传送至信标位置 传送完成后隐身，隐身状态持续片刻", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xE9u, 0x12Eu, "电磁脉冲", "对周围所有敌人造成相当于其当前 生命值一定比例的伤害，侵入敌人 并摧毁附近的敌方屏障", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xF4u, 0x12Eu, "相时而动", "你可以看出敌方英雄的终极技能是否就绪，且对被侵入敌人造成更高伤害", AbilityCategory::Passive, AbilitySlot::Passive, "", true},
};
inline constexpr std::size_t kAbilities_12E_count = 6;

// 末日铁拳 (0x12F) — 7 abilities
inline constexpr Ability kAbilities_12F[] = {
    {0x11Fu, 0x12Fu, "裂地重拳", "跃起并重击地面", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x33Eu, 0x12Fu, "悍猛格挡", "格挡前方的攻击 格挡大量伤害后，强化火箭重拳", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x107u, 0x12Fu, "火箭重拳", "长按可蓄力向前冲锋并将一名敌人击退。将敌人拳击至墙面可造成更大伤害", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x108u, 0x12Fu, "毁天灭地", "按下 %1$s 跃向空中。移动瞄准圈随后按下 %2$s 发动攻击", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x109u, 0x12Fu, "手炮", "可自动装弹的近距离散射武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x10Au, 0x12Fu, "最佳防守……", "技能造成伤害后，自身可生成临时生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
    {0x347u, 0x12Fu, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_12F_count = 7;

// 安娜 (0x13B) — 5 abilities
inline constexpr Ability kAbilities_13B[] = {
    {0xE1u, 0x13Bu, "麻醉镖", "射出飞镖让敌人入眠", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xE3u, 0x13Bu, "生物步枪", "可以治疗盟友并对敌人造成伤害的远距离步枪", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0xE2u, 0x13Bu, "生物手雷", "扔出一枚手雷，治疗盟友并提高其受到的治疗量，同时还可以对敌人造成伤害并使其无法受到治疗", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xE4u, 0x13Bu, "纳米激素", "提高一名队友造成的伤害，同时降低其受到的伤害", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xE5u, 0x13Bu, "瞄准射击", "长按可以开镜瞄准", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
};
inline constexpr std::size_t kAbilities_13B_count = 5;

// 奥丽莎 (0x13E) — 6 abilities
inline constexpr Ability kAbilities_13E[] = {
    {0x31Du, 0x13Eu, "能量标枪", "投出标枪，击晕并击退敌人 敌人撞墙时效果提升", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xEBu, 0x13Eu, "强固防御", "获得临时生命值，降低受到的伤害 并且不可阻挡", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x31Cu, 0x13Eu, "标枪旋击", "旋转标枪，可摧毁飞射物 招架近身攻击，击退敌人 并提高前进速度", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x31Eu, 0x13Eu, "撼地猛刺", "困住并横扫敌人 获得强固防御效果 猛刺伤害随蓄力提升 按下 %1$s 可提前施放猛刺", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x31Fu, 0x13Eu, "强化聚变驱动器", "全自动热量式武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x347u, 0x13Eu, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_13E_count = 6;

// 布丽吉塔 (0x195) — 7 abilities
inline constexpr Ability kAbilities_195[] = {
    {0x1A5u, 0x195u, "集结号令", "获得护甲，强化屏障护盾，并为周围的盟友提供额外生命值", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x1A7u, 0x195u, "鼓舞士气", "对敌人造成伤害会为周围的盟友恢复生命", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
    {0x1A4u, 0x195u, "恢复包", "较短的时间内持续治疗一名盟友。", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x1A3u, 0x195u, "流星飞锤", "向前方甩出连枷，将一名敌人击退", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x1A6u, 0x195u, "火箭连枷", "较大范围的近战攻击", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x1DAu, 0x195u, "屏障护盾", "按住 %1$s 可以在前方展开一道能量屏障", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x1DBu, 0x195u, "能量盾击", "展开屏障护盾后可以向前疾冲 击退一名敌人", AbilityCategory::Ability, AbilitySlot::LMB, "主要攻击模式", false},
};
inline constexpr std::size_t kAbilities_195_count = 7;

// 莫伊拉 (0x1A2) — 5 abilities
inline constexpr Ability kAbilities_1A2[] = {
    {0x14Au, 0x1A2u, "生化之触", "长按治疗前方所有队友。会消耗生化能量", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x149u, 0x1A2u, "辅助攻击模式", "远程光束武器。造成伤害时为你恢复生命并加速恢复生化能量", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x16Du, 0x1A2u, "生化之球", "发射来回弹射的能量球，为附近的盟友恢复生命，或对附近的敌人造成伤害", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x148u, 0x1A2u, "消散", "消失，移动速度加快并变为无敌状态，但无法射击", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x14Cu, 0x1A2u, "聚合射线", "发射一道光束，为盟友恢复生命并对敌人造成伤害", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
};
inline constexpr std::size_t kAbilities_1A2_count = 5;

// 破坏球 (0x1CA) — 7 abilities
inline constexpr Ability kAbilities_1CA[] = {
    {0x189u, 0x1CAu, "四联火炮", "全自动冲锋武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x1EDu, 0x1CAu, "地雷禁区", "部署一大片感应地雷", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x1E8u, 0x1CAu, "工程抓钩", "发射抓钩令铁球在所处区域内高速摆动。可高速撞击敌人造成伤害和击退效果", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", true},
    {0x18Cu, 0x1CAu, "动力铁球", "变成球形，提高最大移动速度", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x198u, 0x1CAu, "重力坠击", "从空中向下发动猛击，将敌人击飞", AbilityCategory::Ability, AbilitySlot::Crouch, "下蹲", false},
    {0x20Fu, 0x1CAu, "感应护盾", "产生临时的额外生命值，附近敌人越多增加的生命值越多。可将部分额外生命值转移给盟友", AbilityCategory::Ability, AbilitySlot::E, "技能 2", true},
    {0x347u, 0x1CAu, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_1CA_count = 7;

// 索杰恩 (0x1EC) — 5 abilities
inline constexpr Ability kAbilities_1EC[] = {
    {0x1C7u, 0x1ECu, "机动滑铲", "贴地滑铲猛冲 可提前高高跳起结束滑铲", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x1C8u, 0x1ECu, "干扰弹", "发射一道能量冲击波 对其中的敌人造成伤害", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x1C9u, 0x1ECu, "电磁炮", "快速射击子弹 命中后产生能量", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x1CAu, 0x1ECu, "充能射击", "消耗存储的能量 射出可以穿透敌人的强力一击", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x1CBu, 0x1ECu, "机体超频", "电磁炮在短时间内自动充能", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
};
inline constexpr std::size_t kAbilities_1EC_count = 5;

// 艾什 (0x200) — 5 abilities
inline constexpr Ability kAbilities_200[] = {
    {0x20Du, 0x200u, "短筒猎枪", "轰击你前方的敌人，同时使你自己后退", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x20Cu, 0x200u, "召唤鲍勃", "派出鲍勃向前冲锋，将敌人击飞到空中，然后用手臂上的火炮攻击他们", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x20Bu, 0x200u, "延时雷管", "投出一捆炸药，在短暂的延迟后爆炸，或者射击炸药立即将其引爆", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x20Au, 0x200u, "毒蛇", "半自动步枪", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x209u, 0x200u, "瞄准射击", "长按可以开镜瞄准，提高射击的伤害与精度，但射速会变慢", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
};
inline constexpr std::size_t kAbilities_200_count = 5;

// 回声 (0x206) — 6 abilities
inline constexpr Ability kAbilities_206[] = {
    {0x26Eu, 0x206u, "黏性炸弹", "发射出一连串黏性炸弹，一段时间之后爆炸", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x26Fu, 0x206u, "人格复制", "选择一个英雄，成为其复制。技能持续期间该目标无法更换英雄", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x270u, 0x206u, "三角射击", "同时发射三发子弹，以三角形分布", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x271u, 0x206u, "飞行", "迅速向前飞行，然后可以在一小段时间内自由飞行", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x2B8u, 0x206u, "聚焦光线", "引导一道光束，持续数秒时间，对生命值低于一半的敌人造成大量伤害", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x2AFu, 0x206u, "滑翔", "下落时按下跳跃键可以滑翔", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
};
inline constexpr std::size_t kAbilities_206_count = 6;

// 巴蒂斯特 (0x221) — 6 abilities
inline constexpr Ability kAbilities_221[] = {
    {0x263u, 0x221u, "愈合冲击", "激活后立即治疗自己和周围盟友，并额外提供持续治疗效果 对生命值低于一半的目标，瞬间治疗量翻倍", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x241u, 0x221u, "维生力场", "投出力场装置，使周围盟友不会死亡。此装置可被摧毁", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x242u, 0x221u, "增幅矩阵", "投出一面矩阵，友方弹药穿过矩阵后伤害和治疗翻倍", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x244u, 0x221u, "生化榴弹枪", "三连发冲锋枪", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x262u, 0x221u, "辅助攻击模式", "发射医疗飞弹，治疗落点周围的盟友", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x264u, 0x221u, "动力战靴", "按住下蹲键可以跳得更高", AbilityCategory::Passive, AbilitySlot::Passive, "下蹲", true},
};
inline constexpr std::size_t kAbilities_221_count = 6;

// 雾子 (0x231) — 6 abilities
inline constexpr Ability kAbilities_231[] = {
    {0x22Fu, 0x231u, "狐", "召唤一只灵狐冲向前方，为置身路径中的盟友提高移动速度、攻击速度和技能冷却速度", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x22Cu, 0x231u, "符", "引导一串能自动飞向目标 盟友的治疗护身符", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x2C8u, 0x231u, "锥", "投出能远距离攻击的苦无", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x22Eu, 0x231u, "瞬", "瞬移至一名盟友身旁", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x2C9u, 0x231u, "铃", "投出一枚护身铃铛，使盟友在短时间内 变为无敌状态，并净化大部分负面效果", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x233u, 0x231u, "攀", "跃上并沿着墙壁攀爬", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
};
inline constexpr std::size_t kAbilities_231_count = 6;

// 渣客女王 (0x236) — 7 abilities
inline constexpr Ability kAbilities_236[] = {
    {0x2C6u, 0x236u, "锯齿利刃（格雷西）", "主动：投掷飞刀。再次使用可将其召回， 并拉回被穿刺的敌人 被动：快速近身攻击或投掷会创伤 敌人，造成持续伤害", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", true},
    {0x2CEu, 0x236u, "命令怒吼", "为你和盟友提供临时生命值 并提高移动速度", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", true},
    {0x2D2u, 0x236u, "散弹枪", "泵动式霰弹枪", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x2D5u, 0x236u, "血斩", "创伤前方的所有敌人，造成持续伤害 每命中一名敌人都会缩短冷却时间", AbilityCategory::Ability, AbilitySlot::E, "技能 2", true},
    {0x2D9u, 0x236u, "轰翻天", "向前冲锋。创伤敌人，造成持续伤害 并使其无法受到治疗", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", true},
    {0x2D0u, 0x236u, "狂血奔涌", "创伤效果的持续伤害会治疗你", AbilityCategory::Passive, AbilitySlot::Passive, "", true},
    {0x347u, 0x236u, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_236_count = 7;

// 西格玛 (0x23B) — 6 abilities
inline constexpr Ability kAbilities_23B[] = {
    {0x289u, 0x23Bu, "动能俘获", "阻挡从前方飞向你的子弹，并将它们转化成额外生命值", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x28Au, 0x23Bu, "质量吸附", "汇聚一团物质投向敌人，将对方击倒", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x28Bu, 0x23Bu, "引力乱流", "操控引力，将敌人先举到空中然后砸向地面", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x28Cu, 0x23Bu, "超能之球", "发射两团引力电荷，在一小段时间后爆炸，造成范围伤害", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x28Du, 0x23Bu, "实验屏障", "按下按键可以制造出悬浮的屏障向外飞出，松开按键使其停止。再次按下会将屏障召回到你身边", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x347u, 0x23Bu, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_23B_count = 6;

// 拉玛刹 (0x28D) — 8 abilities
inline constexpr Ability kAbilities_28D[] = {
    {0x2BFu, 0x28Du, "虚空加速器（智械形态）", "发射一串粒子", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x2C0u, 0x28Du, "猛拳（天罚形态）", "出拳捶击，每次挥拳都会产生一道贯穿能量波", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x2BBu, 0x28Du, "虚空屏障（智械形态）", "在目标位置制造一面屏障", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x2C4u, 0x28Du, "天罚形态", "变为天罚形态，改变攻击方式并获得额外护甲", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", true},
    {0x2C1u, 0x28Du, "铁臂（天罚形态）", "大幅降低来自前方的伤害并降低自身移动速度", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", true},
    {0x2BEu, 0x28Du, "吞噬漩涡", "发射一枚能量球，在地面上爆炸，减速敌人并将其拽向地面。再次激活可提前引爆", AbilityCategory::Ability, AbilitySlot::E, "技能 2", true},
    {0x2C3u, 0x28Du, "诛", "进入天罚形态并生成致命的粒子簇，痛击周围的敌人，只要敌人受到此效果伤害，效果持续时间就会延长", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", true},
    {0x347u, 0x28Du, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_28D_count = 8;

// 生命之梭 (0x291) — 6 abilities
inline constexpr Ability kAbilities_291[] = {
    {0x2CAu, 0x291u, "愈疗灵花", "长按充能治疗冲击， 松开后治疗目标盟友 不使用时会缓慢被动充能", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x2CBu, 0x291u, "棘刺箭雨", "快速发射成对棘刺", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x2D4u, 0x291u, "花瓣平台", "扔出一个平台，踩上后会向上升起 未使用时会归于原位", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x32Bu, 0x291u, "回春疾行", "向行进方向疾冲，并轻微治疗自己", AbilityCategory::Ability, AbilitySlot::Jump, "跳跃", false},
    {0x2CDu, 0x291u, "生命之握", "把一名盟友拉到你的位置， 在飞行过程中提供保护", AbilityCategory::Ability, AbilitySlot::E, "技能 2", true},
    {0x32Cu, 0x291u, "生命之树", "种植一棵树，发芽时立即治疗盟友， 树木存活时会持续产生周期性治疗", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
};
inline constexpr std::size_t kAbilities_291_count = 6;

// 毛加 (0x30A) — 7 abilities
inline constexpr Ability kAbilities_30A[] = {
    {0x328u, 0x30Au, "蛮力冲撞", "向前冲锋，重踏击飞敌人 冲锋时不可阻挡", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x32Au, 0x30Au, "心脏过载", "获得受伤减免，周围盟友造成伤害会为其恢复生命值", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x326u, 0x30Au, "笼中斗", "部署一面屏障将自己和敌人困在其中", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x327u, 0x30Au, "燃火链式机枪（老枪）", "自动武器，多次命中可点燃敌人", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x329u, 0x30Au, "爆烈链式机枪（恰恰）", "自动武器，可对被点燃的敌人造成暴击伤害", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x334u, 0x30Au, "狂战士", "造成暴击伤害会获得临时生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
    {0x347u, 0x30Au, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_30A_count = 7;

// 伊拉锐 (0x31C) — 5 abilities
inline constexpr Ability kAbilities_31C[] = {
    {0x356u, 0x31Cu, "烈日冲击", "向移动方向弹射而出，同时击退敌人。按住跳跃键弹射高度更高", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x355u, 0x31Cu, "治疗光塔", "部署一个可以治疗盟友的光塔", AbilityCategory::Ability, AbilitySlot::E, "技能 2", true},
    {0x353u, 0x31Cu, "桎梏灼日", "发射一颗会爆炸的太阳能量球 被击中的敌人会减速，并在受到大量伤害后爆炸", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x354u, 0x31Cu, "阳焰步枪", "远距离自动充能步枪", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x357u, 0x31Cu, "辅助攻击模式", "消耗太阳能的中距离治疗光束", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
};
inline constexpr std::size_t kAbilities_31C_count = 5;

// 弗蕾娅 (0x32A) — 6 abilities
inline constexpr Ability kAbilities_32A[] = {
    {0x36Bu, 0x32Au, "速射弩", "快速发射自动弩箭", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x37Du, 0x32Au, "瞄准射击", "减缓动势仔细瞄准，射出一支高速爆炸弩箭 使用疾冲可刷新瞄准射击", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x36Cu, 0x32Au, "疾冲", "向移动方向疾冲并刷新瞄准射击", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x460u, 0x32Au, "上升气流", "乘风向上飞起", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x48Du, 0x32Au, "流星索", "发射一枚爆炸流星索，击中敌人后将其束缚并拖拽周围的其他敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x45Au, 0x32Au, "赏金狩猎", "每造成3次最后一击会额外获得终极技能充能", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_32A_count = 6;

// 探奇 (0x32B) — 6 abilities
inline constexpr Ability kAbilities_32B[] = {
    {0x3A5u, 0x32Bu, "智能挖掘钻", "发射一枚震波弹，前进一小段距离后爆炸", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x373u, 0x32Bu, "钻地", "钻入地下，变为无敌状态 按下或长按 %1$s 钻出并伤害敌人", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", true},
    {0x381u, 0x32Bu, "钻头突刺", "在地上或地下向前突刺击退敌人 钻地激活时加快冷却速度", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x3C1u, 0x32Bu, "地壳震击", "发射能造成伤害的冲击波", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x40Du, 0x32Bu, "猛钻", "快速近身攻击造成更高伤害", AbilityCategory::Passive, AbilitySlot::Passive, "快速近身攻击", false},
    {0x42Du, 0x32Bu, "探险家的决心", "使用技能会提供临时护盾", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_32B_count = 6;

// 骇灾 (0x362) — 7 abilities
inline constexpr Ability kAbilities_362[] = {
    {0x420u, 0x362u, "千针雨", "降下一片尖刺雨，定身敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x3DFu, 0x362u, "骨刺", "发射一簇尖刺", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x427u, 0x362u, "尖刺护体", "格挡前方的攻击，向附近敌人发射追踪尖刺 激活时降低受到的伤害并恢复弹药", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x3E0u, 0x362u, "狂跃", "跃向前方。再次激活可劈砍敌人并将其击退", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x449u, 0x362u, "尖刺墙", "发射一堵尖刺墙，对附近的敌人造成伤害并将其击退", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x428u, 0x362u, "翻越", "攀爬矮墙并扒住边缘登上", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
    {0x347u, 0x362u, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_362_count = 7;

// 朱诺 (0x365) — 6 abilities
inline constexpr Ability kAbilities_365[] = {
    {0x3E2u, 0x365u, "医疗冲击枪", "可以治疗盟友并对敌人造成伤害的连发武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", true},
    {0x408u, 0x365u, "脉冲星飞雷", "按下 %1$s 锁定目标，随后按下 %2$s 发射追踪飞雷 持续治疗盟友并对敌人造成伤害", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x417u, 0x365u, "滑翔推进", "提高移动速度并沿水平方向滑翔", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x41Eu, 0x365u, "超能环域", "部署一道环域 盟友穿过环域后，移动速度提升", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x42Fu, 0x365u, "轨道射线", "召唤一道射线向前移动 治疗盟友并提高其造成的伤害", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x41Au, 0x365u, "火星套靴", "在空中时，按下 %1$s 可以二段跳 按住 %1$s 可以悬浮在空中", AbilityCategory::Passive, AbilitySlot::Passive, "跳跃", false},
};
inline constexpr std::size_t kAbilities_365_count = 6;

// 无漾 (0x3C3) — 5 abilities
inline constexpr Ability kAbilities_3C3[] = {
    {0x5D8u, 0x3C3u, "玄武杖", "发射一颗伤害性水珠 按住可控制水珠轨迹并强化其爆炸", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x630u, 0x3C3u, "翻江浪", "劈出一道向前的波浪，提高盟友 受到的治疗量并击退敌人", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x49Du, 0x3C3u, "飞流步", "乘波而行，提高移动速度和跳跃高度", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x5DAu, 0x3C3u, "养神泉", "用一股可以被动治疗的泉水环绕一名盟友。对目标按住会消耗资源并手动快速治疗", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x85Eu, 0x3C3u, "惊涛破", "水流聚合成球，保护一名盟友或自身，一小段时间后水球爆炸，击倒敌人并为受保护的目标提供大量治疗", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
};
inline constexpr std::size_t kAbilities_3C3_count = 5;

// 斩仇 (0x472) — 7 abilities
inline constexpr Ability kAbilities_472[] = {
    {0x854u, 0x472u, "旋风疾步", "向前猛冲并回旋劈斩", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0x852u, 0x472u, "飞空斩击", "向面朝方向扔出大剑，接着飞到剑旁", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0x851u, 0x472u, "帕拉蒂尼之牙", "高强度光束巨剑 连击会以一记势大力沉的竖直劈斩收尾", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0x855u, 0x472u, "招架姿态", "举剑格挡，降低前方受到的伤害并招架近身攻击。格挡伤害会消耗能量", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0x856u, 0x472u, "锋锐剑气", "可在招架姿态激活时使用 消耗能量，发射一道宽幅能量波", AbilityCategory::Ability, AbilitySlot::LMB, "主要攻击模式", false},
    {0x859u, 0x472u, "斩地巨剑", "蓄势猛劈，击破大部分防御，对前方的敌人造成巨量伤害", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0x853u, 0x472u, "越战越勇", "斩击敌人会加快移动速度和攻击速度", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_472_count = 7;

// 金驭 (0x4C4) — 7 abilities
inline constexpr Ability kAbilities_4C4[] = {
    {0xC53u, 0x4C4u, "光子马格南", "能汇聚为强力一击的中距离光束", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0xC6Du, 0x4C4u, "屏障阵列", "构造一道分段式屏障", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xC90u, 0x4C4u, "音速斥力场", "击退敌人，若击退至墙面还可将其击晕", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xCABu, 0x4C4u, "爆能水晶", "投出一枚爆能水晶，再次激活即可引爆", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xC91u, 0x4C4u, "全景牢笼", "发射一道高强度光束屏障囚禁敌人，消失时会引爆", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xCA2u, 0x4C4u, "护盾重构", "技能造成伤害会恢复护盾", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
    {0x347u, 0x4C4u, "职责：重装", "降低受到治疗和伤害时给予的 终极技能充能 提高预设职责模式下的基础生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_4C4_count = 7;

// 埃姆雷 (0x4D8) — 6 abilities
inline constexpr Ability kAbilities_4D8[] = {
    {0xC62u, 0x4D8u, "合成连发步枪", "三连发武器", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0xC73u, 0x4D8u, "瞄准射击", "长按可以开镜瞄准，提高射击精度，扩大衰减射程", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xC64u, 0x4D8u, "虹吸冲击枪", "临时使用装配生命汲取爆炸子弹的半自动手枪 使用时提高移动速度和跳跃高度", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xC63u, 0x4D8u, "赛博手雷", "扔出一枚手雷，弹跳后会在短时间内引爆", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xC7Au, 0x4D8u, "覆盖协议", "启动覆盖程序，将你变为人形兵器", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xE1Cu, 0x4D8u, "机变体征", "被动生命值恢复激活速度加快，并在激活时立即恢复30点生命值", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_4D8_count = 6;

// 安燃 (0x4DD) — 7 abilities
inline constexpr Ability kAbilities_4DD[] = {
    {0xC88u, 0x4DDu, "朱雀扇", "能扇出炽烈火焰的折扇", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0xC89u, 0x4DDu, "煽火风", "能强化燃烧伤害的灼热狂风", AbilityCategory::Weapon, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xCB1u, 0x4DDu, "怒炎冲", "向前疾行，对击中的敌人造成伤害", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xCC1u, 0x4DDu, "熠闪舞", "闪避所有伤害并打击周围敌人，每击中一名敌人都会治疗自身", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xD06u, 0x4DDu, "朱羽焚", "向前猛冲，击中时爆炸并立即点燃敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xE0Eu, 0x4DDu, "朱魂返", "阵亡时，在炽烈的爆炸中复生", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xC8Au, 0x4DDu, "焚身焰", "用火焰攻击命中敌人可将其点燃", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_4DD_count = 7;

// 瑞稀 (0x4E3) — 6 abilities
inline constexpr Ability kAbilities_4E3[] = {
    {0xD73u, 0x4E3u, "御魂镰刃", "扔出能对敌人造成伤害的弹跳镰刃", AbilityCategory::Weapon, AbilitySlot::LMB, "主要攻击模式", false},
    {0xD3Eu, 0x4E3u, "疗魂斗笠", "扔出能在盟友间弹跳的斗笠并为其治疗", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xCDCu, 0x4E3u, "缚魂锁链", "扔出锁链，限制一名敌人的移动", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xD98u, 0x4E3u, "替魂纸人", "向前一跃，加快移动速度。再次激活会瞬移回原地", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xDEDu, 0x4E3u, "护魂结界", "生成一道结界，能治疗盟友并吸收结界外发射的敌方射弹", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xDF3u, 0x4E3u, "安魂灵气", "治疗周围盟友。对他人造成伤害或治疗时效果会变得越来越强", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_4E3_count = 6;

// 飞天猫 (0x516) — 6 abilities
inline constexpr Ability kAbilities_516[] = {
    {0xD77u, 0x516u, "生物猫爪弹", "可治疗盟友并对敌人造成伤害的中距离扩散子弹", AbilityCategory::Weapon, AbilitySlot::None, "", false},
    {0xD5Eu, 0x516u, "咻咻飞", "沿移动方向加速。运输其他玩家时减缓燃料恢复速度", AbilityCategory::Ability, AbilitySlot::RMB, "辅助攻击模式", false},
    {0xD5Fu, 0x516u, "救生索", "切换为运输模式，盟友可抓住救生索任你拖拽。加快移动速度并治疗被拖拽的盟友", AbilityCategory::Ability, AbilitySlot::Shift, "技能 1", false},
    {0xD60u, 0x516u, "呼噜噜", "脉冲式范围治疗，频率随时间提高。激活时击退周围敌人", AbilityCategory::Ability, AbilitySlot::E, "技能 2", false},
    {0xDEBu, 0x516u, "猫猫劫", "冲向地面位置，击倒敌人并拴锁离你最近的敌人", AbilityCategory::UltimateAbility, AbilitySlot::Ult, "技能 3", false},
    {0xD61u, 0x516u, "喷气背包", "永久飞行", AbilityCategory::Passive, AbilitySlot::Passive, "", false},
};
inline constexpr std::size_t kAbilities_516_count = 6;

/// Get the abilities for a hero. Returns false if unknown hero.
inline bool GetHeroAbilities(uint32_t hero_id, const Ability*& out_ptr, std::size_t& out_count) noexcept {
    switch (hero_id) {
    case 0x2u: out_ptr = kAbilities_2; out_count = kAbilities_2_count; return true;
    case 0x3u: out_ptr = kAbilities_3; out_count = kAbilities_3_count; return true;
    case 0x4u: out_ptr = kAbilities_4; out_count = kAbilities_4_count; return true;
    case 0x5u: out_ptr = kAbilities_5; out_count = kAbilities_5_count; return true;
    case 0x6u: out_ptr = kAbilities_6; out_count = kAbilities_6_count; return true;
    case 0x7u: out_ptr = kAbilities_7; out_count = kAbilities_7_count; return true;
    case 0x8u: out_ptr = kAbilities_8; out_count = kAbilities_8_count; return true;
    case 0x9u: out_ptr = kAbilities_9; out_count = kAbilities_9_count; return true;
    case 0xAu: out_ptr = kAbilities_A; out_count = kAbilities_A_count; return true;
    case 0x15u: out_ptr = kAbilities_15; out_count = kAbilities_15_count; return true;
    case 0x16u: out_ptr = kAbilities_16; out_count = kAbilities_16_count; return true;
    case 0x20u: out_ptr = kAbilities_20; out_count = kAbilities_20_count; return true;
    case 0x29u: out_ptr = kAbilities_29; out_count = kAbilities_29_count; return true;
    case 0x40u: out_ptr = kAbilities_40; out_count = kAbilities_40_count; return true;
    case 0x42u: out_ptr = kAbilities_42; out_count = kAbilities_42_count; return true;
    case 0x65u: out_ptr = kAbilities_65; out_count = kAbilities_65_count; return true;
    case 0x68u: out_ptr = kAbilities_68; out_count = kAbilities_68_count; return true;
    case 0x6Eu: out_ptr = kAbilities_6E; out_count = kAbilities_6E_count; return true;
    case 0x79u: out_ptr = kAbilities_79; out_count = kAbilities_79_count; return true;
    case 0x7Au: out_ptr = kAbilities_7A; out_count = kAbilities_7A_count; return true;
    case 0xDDu: out_ptr = kAbilities_DD; out_count = kAbilities_DD_count; return true;
    case 0x12Eu: out_ptr = kAbilities_12E; out_count = kAbilities_12E_count; return true;
    case 0x12Fu: out_ptr = kAbilities_12F; out_count = kAbilities_12F_count; return true;
    case 0x13Bu: out_ptr = kAbilities_13B; out_count = kAbilities_13B_count; return true;
    case 0x13Eu: out_ptr = kAbilities_13E; out_count = kAbilities_13E_count; return true;
    case 0x195u: out_ptr = kAbilities_195; out_count = kAbilities_195_count; return true;
    case 0x1A2u: out_ptr = kAbilities_1A2; out_count = kAbilities_1A2_count; return true;
    case 0x1CAu: out_ptr = kAbilities_1CA; out_count = kAbilities_1CA_count; return true;
    case 0x1ECu: out_ptr = kAbilities_1EC; out_count = kAbilities_1EC_count; return true;
    case 0x200u: out_ptr = kAbilities_200; out_count = kAbilities_200_count; return true;
    case 0x206u: out_ptr = kAbilities_206; out_count = kAbilities_206_count; return true;
    case 0x221u: out_ptr = kAbilities_221; out_count = kAbilities_221_count; return true;
    case 0x231u: out_ptr = kAbilities_231; out_count = kAbilities_231_count; return true;
    case 0x236u: out_ptr = kAbilities_236; out_count = kAbilities_236_count; return true;
    case 0x23Bu: out_ptr = kAbilities_23B; out_count = kAbilities_23B_count; return true;
    case 0x28Du: out_ptr = kAbilities_28D; out_count = kAbilities_28D_count; return true;
    case 0x291u: out_ptr = kAbilities_291; out_count = kAbilities_291_count; return true;
    case 0x30Au: out_ptr = kAbilities_30A; out_count = kAbilities_30A_count; return true;
    case 0x31Cu: out_ptr = kAbilities_31C; out_count = kAbilities_31C_count; return true;
    case 0x32Au: out_ptr = kAbilities_32A; out_count = kAbilities_32A_count; return true;
    case 0x32Bu: out_ptr = kAbilities_32B; out_count = kAbilities_32B_count; return true;
    case 0x362u: out_ptr = kAbilities_362; out_count = kAbilities_362_count; return true;
    case 0x365u: out_ptr = kAbilities_365; out_count = kAbilities_365_count; return true;
    case 0x3C3u: out_ptr = kAbilities_3C3; out_count = kAbilities_3C3_count; return true;
    case 0x472u: out_ptr = kAbilities_472; out_count = kAbilities_472_count; return true;
    case 0x4C4u: out_ptr = kAbilities_4C4; out_count = kAbilities_4C4_count; return true;
    case 0x4D8u: out_ptr = kAbilities_4D8; out_count = kAbilities_4D8_count; return true;
    case 0x4DDu: out_ptr = kAbilities_4DD; out_count = kAbilities_4DD_count; return true;
    case 0x4E3u: out_ptr = kAbilities_4E3; out_count = kAbilities_4E3_count; return true;
    case 0x516u: out_ptr = kAbilities_516; out_count = kAbilities_516_count; return true;
    default: out_ptr = nullptr; out_count = 0; return false;
    }
}

/// Find a hero's ability bound to a specific slot. Returns nullptr if none.
/// Useful: e.g. FindAbilityBySlot(0x2, AbilitySlot::Shift) → Reaper Wraith Form.
inline const Ability* FindAbilityBySlot(uint32_t hero_id, AbilitySlot slot) noexcept {
    const Ability* arr = nullptr; std::size_t n = 0;
    if (!GetHeroAbilities(hero_id, arr, n)) return nullptr;
    for (std::size_t i = 0; i < n; ++i) {
        if (arr[i].slot == slot) return &arr[i];
    }
    return nullptr;
}

/// Linear search across all heroes for a loadout_id. O(N) — for one-off lookup only.
inline const Ability* FindAbilityByLoadoutId(uint32_t loadout_id) noexcept {
    const Ability* arr = nullptr; std::size_t n = 0;
    // iterate every hero's table
    for (uint32_t hid = 0; hid < 0x600; ++hid) {
        if (!GetHeroAbilities(hid, arr, n)) continue;
        for (std::size_t i = 0; i < n; ++i) {
            if (arr[i].loadout_id == loadout_id) return &arr[i];
        }
    }
    return nullptr;
}

inline const char* SlotName(AbilitySlot s) noexcept {
    switch (s) {
    case AbilitySlot::None: return "None";
    case AbilitySlot::LMB: return "LMB";
    case AbilitySlot::RMB: return "RMB";
    case AbilitySlot::Shift: return "Shift";
    case AbilitySlot::E: return "E";
    case AbilitySlot::Ult: return "Ult";
    case AbilitySlot::Passive: return "Passive";
    case AbilitySlot::Jump: return "Jump";
    case AbilitySlot::Crouch: return "Crouch";
    case AbilitySlot::CrouchToggle: return "CrouchToggle";
    case AbilitySlot::Interact: return "Interact";
    case AbilitySlot::Melee: return "Melee";
    case AbilitySlot::Reload: return "Reload";
    case AbilitySlot::NextWeapon: return "NextWeapon";
    case AbilitySlot::EquipWeapon1: return "EquipWeapon1";
    }
    return "?";
}

inline const char* CategoryName(AbilityCategory c) noexcept {
    switch (c) {
    case AbilityCategory::Weapon: return "Weapon";
    case AbilityCategory::Ability: return "Ability";
    case AbilityCategory::UltimateAbility: return "UltimateAbility";
    case AbilityCategory::Passive: return "Passive";
    case AbilityCategory::Perk: return "Perk";
    case AbilityCategory::HeroStats: return "HeroStats";
    case AbilityCategory::Subrole: return "Subrole";
    }
    return "?";
}

} // namespace sdk
} // namespace ow
