// ============================================================================
// AUTO-GENERATED by scripts/generate_sdk_v2.py
// DO NOT EDIT BY HAND. Source of truth:
//   - blueprint_editor/output/var_dictionary.json (statescript var names)
//   - output/dump_json/heroes.json + loadouts.json (CASC dump)
// Regenerate: python3 scripts/generate_sdk_v2.py
// ============================================================================
#pragma once

#include <cstdint>
#include <cstddef>

// herokitdump.hpp — Per-hero kit rollup: loadouts + graph actions + var footprint
// 50 heroes, derived from abilities.json (no hardcoded knowledge).
//
// Use this to answer questions like:
//   'Which state vars does Genji Deflect write?'  → kHeroKit_5.graphs[n].write_var_ids
//   'What entity does Ashe's Dynamite spawn?'     → kHeroKit_N.graphs[n].spawned_entity_id
//   'Does this hero have a deflect?'              → kHeroKit_N.has_deflect

namespace ow {
namespace sdk {

struct HeroKitGraph {
    uint32_t    graph_index;
    int16_t     slot_index;
    uint16_t    total_nodes;
    uint16_t    weapon_volley_count;
    uint16_t    modify_health_count;
    uint16_t    create_entity_count;
    uint16_t    set_var_count;
    uint16_t    chase_var_count;
    uint16_t    deflect_count;
    uint16_t    health_pool_count;
    uint32_t    first_projectile_entity_id;   // 0 if none
    const char* first_projectile_name;        // first named projectile from this graph
    const char* likely_loadout_name;          // positional guess by slot_index
};

struct HeroKit {
    uint32_t          hero_id;
    const char*       hero_name;
    uint16_t          graph_count;
    bool              has_deflect;             // any graph with a DeflectProjectiles node
    bool              has_projectile_weapon;   // any WeaponVolley with a spawned entity
    bool              has_beam_weapon;         // any TrackTargets node (heuristic via node histogram)
    const HeroKitGraph* graphs;
};

// 死神 (0x2) — 14 graphs
inline constexpr HeroKitGraph kHeroKit_2_graphs[] = {
    {0x4Bu, 0, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "死亡绽放"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "地狱火霰弹枪"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "暗影步"},
    {0x3DCEu, 3, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", "收割"},
    {0x8B6u, 4, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "幽灵形态"},
    {0x3E9Bu, 5, 46u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "恐怖扳机"},
    {0x20u, 6, 83u, 0u, 0u, 0u, 7u, 0u, 0u, 0u, 0x0u, "", ""},
    {0xF2u, 7, 212u, 0u, 0u, 1u, 21u, 3u, 0u, 0u, 0x1F0Eu, "死神_暗影步_Spawned", ""},
    {0x44u, 8, 117u, 1u, 1u, 0u, 7u, 0u, 0u, 0u, 0x1320u, "死神_死亡绽放_Projectile", ""},
    {0x75u, 9, 66u, 0u, 1u, 0u, 11u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x51EAu, 10, 34u, 0u, 1u, 1u, 0u, 0u, 0u, 0u, 0x4C9Au, "死神_收割_Spawned", ""},
    {0x5016u, 11, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x58B9u, 12, 25u, 0u, 0u, 0u, 4u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5D64u, 13, 44u, 1u, 0u, 0u, 3u, 3u, 0u, 0u, 0x4Au, "死神_恐怖扳机_Projectile", ""},
};
inline constexpr std::size_t kHeroKit_2_graphs_count = 14;

// 猎空 (0x3) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_3_graphs[] = {
    {0x32FCu, 0, 39u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "闪现"},
    {0x1Au, 1, 273u, 0u, 6u, 2u, 39u, 4u, 0u, 1u, 0x0u, "", "闪回"},
    {0x24u, 2, 226u, 0u, 4u, 0u, 28u, 4u, 0u, 1u, 0x0u, "", "脉冲炸弹"},
    {0x34u, 3, 136u, 2u, 1u, 0u, 16u, 0u, 0u, 0u, 0x45u, "猎空_脉冲炸弹_Projectile", "脉冲双枪"},
    {0x33u, 4, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", ""},
    {0x43u, 5, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x4Bu, 6, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3Du, 7, 99u, 0u, 1u, 0u, 7u, 1u, 0u, 2u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51EEu, 10, 31u, 0u, 1u, 0u, 0u, 0u, 0u, 1u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_3_graphs_count = 11;

// 天使 (0x4) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_4_graphs[] = {
    {0x3345u, 0, 73u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "天使之杖"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "守护天使"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "天使之杖"},
    {0x6Eu, 3, 245u, 0u, 1u, 0u, 37u, 3u, 0u, 0u, 0x0u, "", "重生"},
    {0x71u, 4, 209u, 0u, 4u, 0u, 24u, 4u, 0u, 0u, 0x0u, "", "快速治疗"},
    {0x5D59u, 5, 65u, 0u, 1u, 0u, 6u, 2u, 0u, 0u, 0x0u, "", "天使冲击枪"},
    {0xCAu, 6, 287u, 0u, 1u, 0u, 28u, 3u, 0u, 2u, 0x0u, "", "天使降临"},
    {0x43u, 7, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "迅捷恢复"},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "女武神"},
    {0x10DAu, 9, 103u, 0u, 1u, 0u, 5u, 3u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 10, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5161u, 11, 13u, 0u, 1u, 0u, 0u, 0u, 0u, 1u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_4_graphs_count = 12;

// 半藏 (0x5) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_5_graphs[] = {
    {0x4BE7u, 0, 29u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "竜"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "音"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "岚"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "风"},
    {0xC1u, 4, 29u, 0u, 0u, 0u, 2u, 0u, 0u, 0u, 0x0u, "", "攀"},
    {0x146Au, 5, 51u, 0u, 0u, 0u, 6u, 3u, 0u, 0u, 0x0u, "", "跃"},
    {0x10Cu, 6, 144u, 0u, 0u, 0u, 30u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x101u, 7, 95u, 2u, 0u, 0u, 6u, 0u, 0u, 0u, 0x34Fu, "半藏_竜_Projectile", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51E7u, 10, 68u, 0u, 0u, 0u, 5u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 11, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_5_graphs_count = 12;

// 托比昂 (0x6) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_6_graphs[] = {
    {0x38D0u, 0, 47u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "部署炮台"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "热力过载"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "熔火核心"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "铆钉枪"},
    {0x1684u, 4, 145u, 0u, 4u, 1u, 14u, 0u, 0u, 1u, 0x478Au, "托比昂_slot4_Spawned", "辅助攻击模式"},
    {0x16C5u, 5, 121u, 1u, 0u, 0u, 10u, 0u, 0u, 0u, 0x2931u, "托比昂_部署炮台_Projectile", "锻造锤"},
    {0x16DAu, 6, 119u, 1u, 0u, 0u, 12u, 3u, 0u, 0u, 0x2902u, "托比昂_熔火核心_Projectile", ""},
    {0x1721u, 7, 109u, 0u, 0u, 0u, 14u, 3u, 0u, 1u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51F6u, 10, 43u, 0u, 0u, 0u, 3u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_6_graphs_count = 11;

// 莱因哈特 (0x7) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_7_graphs[] = {
    {0x3286u, 0, 60u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "冲锋"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "裂地猛击"},
    {0x7Du, 2, 351u, 0u, 9u, 0u, 33u, 7u, 0u, 0u, 0x0u, "", "烈焰打击"},
    {0x4Bu, 3, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "火箭重锤"},
    {0x95u, 4, 253u, 0u, 3u, 0u, 24u, 3u, 0u, 0u, 0x0u, "", "屏障力场"},
    {0xA4u, 5, 25u, 0u, 0u, 0u, 6u, 0u, 0u, 0u, 0x0u, "", "职责：重装"},
    {0xBEu, 6, 180u, 0u, 2u, 0u, 22u, 0u, 0u, 0u, 0x0u, "", ""},
    {0xE2u, 7, 193u, 1u, 1u, 0u, 27u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 10, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x514Cu, 11, 83u, 0u, 2u, 0u, 9u, 1u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_7_graphs_count = 12;

// 法老之鹰 (0x8) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_8_graphs[] = {
    {0x3B6Eu, 0, 72u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "火箭弹幕"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "推进背包"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "震荡冲击"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "火箭发射器"},
    {0x8B6u, 4, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "悬浮背包"},
    {0x74u, 5, 221u, 1u, 1u, 0u, 27u, 6u, 0u, 3u, 0x4746u, "法老之鹰_slot5_Projectile", "疾冲背包"},
    {0x25u, 6, 238u, 1u, 1u, 0u, 16u, 8u, 0u, 0u, 0x52u, "法老之鹰_火箭弹幕_Projectile", ""},
    {0x27u, 7, 150u, 1u, 3u, 0u, 21u, 2u, 0u, 0u, 0x470Du, "法老之鹰_推进背包_Projectile", ""},
    {0x2Bu, 8, 217u, 2u, 2u, 0u, 8u, 3u, 0u, 0u, 0x410Cu, "法老之鹰_火箭弹幕_Projectile", ""},
    {0x7Bu, 9, 139u, 5u, 0u, 0u, 20u, 3u, 0u, 0u, 0x10Fu, "法老之鹰_震荡冲击_Projectile", ""},
    {0x4B92u, 10, 75u, 0u, 1u, 0u, 5u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51E9u, 11, 44u, 1u, 0u, 0u, 0u, 1u, 0u, 0u, 0x52u, "法老之鹰_火箭弹幕_Projectile", ""},
};
inline constexpr std::size_t kHeroKit_8_graphs_count = 12;

// 温斯顿 (0x9) — 10 graphs
inline constexpr HeroKitGraph kHeroKit_9_graphs[] = {
    {0x332Du, 0, 64u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "喷射背包"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "原始暴怒"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "屏障发射器"},
    {0xFAu, 3, 88u, 0u, 0u, 0u, 12u, 0u, 0u, 0u, 0x0u, "", "特斯拉炮"},
    {0x109u, 4, 243u, 0u, 3u, 0u, 24u, 6u, 0u, 2u, 0x0u, "", "辅助攻击模式"},
    {0x43u, 5, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "职责：重装"},
    {0x10Au, 6, 259u, 0u, 4u, 0u, 21u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x120u, 7, 175u, 0u, 2u, 0u, 19u, 3u, 0u, 2u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51E1u, 9, 20u, 0u, 1u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_9_graphs_count = 10;

// 黑百合 (0xA) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_A_graphs[] = {
    {0x4BE6u, 0, 36u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "抓钩"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "红外侦测"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "剧毒诡雷"},
    {0x56u, 3, 71u, 2u, 0u, 0u, 9u, 0u, 0u, 0u, 0xAFu, "黑百合_剧毒诡雷_Projectile", "黑百合之吻"},
    {0x5Au, 4, 198u, 0u, 2u, 0u, 29u, 7u, 0u, 0u, 0x0u, "", "瞄准射击"},
    {0x43u, 5, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x67u, 6, 56u, 0u, 0u, 0u, 5u, 3u, 0u, 0u, 0x0u, "", ""},
    {0x76u, 7, 72u, 0u, 0u, 1u, 9u, 8u, 0u, 0u, 0x4742u, "黑百合_slot7_Spawned", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 9, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51EFu, 10, 16u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_A_graphs_count = 11;

// 堡垒 (0x15) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_15_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "A-36战术榴弹"},
    {0x4Bu, 1, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "切换模式"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "侦察模式"},
    {0x12Fu, 3, 285u, 0u, 0u, 0u, 49u, 11u, 0u, 1u, 0x0u, "", "强攻模式"},
    {0x13Au, 4, 100u, 2u, 0u, 0u, 17u, 6u, 0u, 0u, 0x207u, "堡垒_强攻模式_Projectile", "火炮模式"},
    {0x163u, 5, 67u, 0u, 0u, 0u, 10u, 8u, 0u, 0u, 0x0u, "", "抗击装甲"},
    {0x23Bu, 6, 79u, 2u, 0u, 0u, 5u, 3u, 0u, 0u, 0x3EFDu, "堡垒_火炮模式_Projectile", ""},
    {0x3045u, 7, 58u, 1u, 0u, 0u, 3u, 1u, 0u, 0u, 0x3F69u, "堡垒_A-36战术榴弹_Projectile", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x4032u, 10, 43u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51E4u, 11, 26u, 0u, 1u, 0u, 0u, 0u, 0u, 1u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_15_graphs_count = 12;

// 秩序之光 (0x16) — 10 graphs
inline constexpr HeroKitGraph kHeroKit_16_graphs[] = {
    {0x34C1u, 0, 56u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "光子发射器"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "辅助攻击模式"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "哨戒炮"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "光子屏障"},
    {0x156Bu, 4, 184u, 0u, 1u, 0u, 29u, 4u, 0u, 0u, 0x0u, "", "传送面板"},
    {0x157Eu, 5, 120u, 1u, 0u, 0u, 28u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x1A3u, 6, 106u, 0u, 0u, 0u, 8u, 2u, 0u, 1u, 0x0u, "", ""},
    {0x1571u, 7, 271u, 0u, 0u, 0u, 32u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51EDu, 9, 15u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_16_graphs_count = 10;

// 禅雅塔 (0x20) — 10 graphs
inline constexpr HeroKitGraph kHeroKit_20_graphs[] = {
    {0x3601u, 0, 46u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "灭"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "辅助攻击模式"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "乱"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "谐"},
    {0x3692u, 4, 175u, 0u, 0u, 0u, 20u, 2u, 0u, 0u, 0x0u, "", "圣"},
    {0x17Bu, 5, 252u, 0u, 2u, 0u, 20u, 3u, 0u, 0u, 0x0u, "", "蹬"},
    {0x18Du, 6, 146u, 0u, 2u, 1u, 16u, 4u, 0u, 2u, 0x0u, "", ""},
    {0x3698u, 7, 136u, 0u, 1u, 0u, 19u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51F5u, 9, 47u, 0u, 2u, 0u, 2u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_20_graphs_count = 10;

// 源氏 (0x29) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_29_graphs[] = {
    {0x346Fu, 0, 37u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "斩"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "闪"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "影"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "镖"},
    {0x157u, 4, 129u, 0u, 0u, 0u, 9u, 0u, 0u, 0u, 0x0u, "", "辅助攻击模式"},
    {0x317u, 5, 167u, 0u, 0u, 0u, 23u, 3u, 0u, 0u, 0x0u, "", "灵"},
    {0x1DBu, 6, 177u, 0u, 3u, 0u, 23u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3A3u, 7, 301u, 2u, 0u, 0u, 32u, 2u, 2u, 0u, 0x7CAu, "源氏_闪_Projectile", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5160u, 10, 49u, 0u, 3u, 0u, 3u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 11, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_29_graphs_count = 12;

// 路霸 (0x40) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_40_graphs[] = {
    {0x3C5Fu, 0, 54u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "鸡飞狗跳"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "爆裂枪"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "辅助攻击模式"},
    {0x36C7u, 3, 320u, 0u, 2u, 0u, 28u, 8u, 0u, 0u, 0x0u, "", "链钩"},
    {0x1EFu, 4, 110u, 0u, 0u, 0u, 19u, 4u, 1u, 0u, 0x0u, "", "呼吸器"},
    {0x1F1u, 6, 138u, 1u, 0u, 0u, 10u, 1u, 0u, 0u, 0x44F0u, "路霸_slot6_Projectile", ""},
    {0x43u, 7, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x240u, 8, 208u, 1u, 1u, 0u, 20u, 5u, 0u, 0u, 0x4503u, "路霸_呼吸器_Projectile", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 10, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51DFu, 11, 55u, 0u, 3u, 0u, 3u, 1u, 0u, 1u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_40_graphs_count = 11;

// 卡西迪 (0x42) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_42_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "神射手"},
    {0x43u, 1, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "战术翻滚"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "闪光弹"},
    {0x1ECu, 3, 36u, 0u, 0u, 0u, 11u, 0u, 0u, 0u, 0x0u, "", "维和者"},
    {0x22Fu, 4, 175u, 0u, 1u, 0u, 27u, 6u, 0u, 0u, 0x0u, "", "连射"},
    {0x1F0u, 5, 83u, 0u, 0u, 0u, 10u, 3u, 0u, 0u, 0x0u, "", ""},
    {0x1E9u, 6, 68u, 3u, 0u, 0u, 4u, 0u, 0u, 0u, 0x37Du, "卡西迪_闪光弹_Projectile", ""},
    {0x8B6u, 7, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 8, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x32C4u, 9, 43u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51E5u, 10, 18u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 11, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_42_graphs_count = 12;

// 狂鼠 (0x65) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_65_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "榴弹发射器"},
    {0x43u, 1, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "震荡地雷"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "捕兽夹"},
    {0x22Au, 3, 125u, 7u, 1u, 0u, 10u, 1u, 0u, 0u, 0x515u, "狂鼠_临别礼物_Projectile", "炸弹轮胎"},
    {0x232u, 4, 134u, 0u, 0u, 0u, 19u, 2u, 0u, 0u, 0x0u, "", "临别礼物"},
    {0x96Au, 5, 254u, 2u, 0u, 0u, 35u, 5u, 0u, 0u, 0xF9Bu, "狂鼠_震荡地雷_Projectile", ""},
    {0x9BAu, 6, 66u, 1u, 0u, 0u, 5u, 0u, 0u, 0u, 0x11A9u, "狂鼠_捕兽夹_Projectile", ""},
    {0x336Bu, 7, 56u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51E8u, 10, 59u, 1u, 0u, 0u, 1u, 4u, 0u, 0u, 0x515u, "狂鼠_临别礼物_Projectile", ""},
};
inline constexpr std::size_t kHeroKit_65_graphs_count = 11;

// 查莉娅 (0x68) — 10 graphs
inline constexpr HeroKitGraph kHeroKit_68_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "重力喷涌"},
    {0x4Bu, 1, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "粒子屏障"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "投射屏障"},
    {0x242u, 3, 219u, 0u, 3u, 0u, 30u, 6u, 0u, 2u, 0x0u, "", "粒子炮"},
    {0x324Bu, 4, 225u, 0u, 0u, 0u, 25u, 7u, 0u, 0u, 0x0u, "", "辅助攻击模式"},
    {0x25Fu, 5, 67u, 3u, 0u, 0u, 2u, 0u, 0u, 0u, 0x8CEu, "查莉娅_重力喷涌_Projectile", "能量转换"},
    {0x8B6u, 6, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "职责：重装"},
    {0x3ABAu, 7, 56u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 8, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x515Bu, 9, 29u, 0u, 0u, 0u, 5u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_68_graphs_count = 10;

// 士兵：76 (0x6E) — 13 graphs
inline constexpr HeroKitGraph kHeroKit_6E_graphs[] = {
    {0x3309u, 0, 50u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "疾跑"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "生物力场"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "重型脉冲步枪"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "螺旋飞弹"},
    {0x251u, 4, 57u, 0u, 1u, 0u, 3u, 0u, 0u, 1u, 0x0u, "", "战术目镜"},
    {0x255u, 5, 122u, 0u, 1u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x257u, 6, 122u, 3u, 1u, 0u, 12u, 1u, 0u, 0u, 0x72Du, "士兵：76_生物力场_Projectile", ""},
    {0x259u, 7, 170u, 0u, 0u, 0u, 17u, 8u, 0u, 0u, 0x0u, "", ""},
    {0x91Bu, 8, 5u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 10, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 11, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x515Cu, 12, 29u, 0u, 0u, 0u, 3u, 1u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_6E_graphs_count = 13;

// 卢西奥 (0x79) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_79_graphs[] = {
    {0x337Du, 0, 58u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "切歌"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "强音"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "音速扩音器"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "音波"},
    {0x263u, 4, 322u, 1u, 4u, 0u, 57u, 12u, 0u, 1u, 0x431Fu, "卢西奥_slot4_Projectile", "音障"},
    {0x266u, 5, 129u, 0u, 0u, 0u, 13u, 0u, 0u, 0u, 0x0u, "", "滑墙"},
    {0x277u, 6, 131u, 0u, 2u, 0u, 19u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x73Au, 7, 240u, 0u, 2u, 0u, 27u, 7u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5162u, 9, 58u, 0u, 0u, 0u, 8u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 10, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_79_graphs_count = 11;

// D.Va (0x7A) — 8 graphs
inline constexpr HeroKitGraph kHeroKit_7A_graphs[] = {
    {0x348Cu, 0, 20u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "推进器"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "防御矩阵"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "自毁"},
    {0x4Bu, 3, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "聚变机炮"},
    {0x26Au, 4, 306u, 0u, 5u, 0u, 22u, 3u, 0u, 1u, 0x0u, "", "微型飞弹"},
    {0xB49u, 5, 97u, 0u, 0u, 0u, 11u, 1u, 1u, 1u, 0x0u, "", "弹射！"},
    {0x8B6u, 6, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "呼叫机甲"},
    {0x514Du, 7, 54u, 0u, 2u, 0u, 1u, 3u, 0u, 1u, 0x0u, "", "光枪"},
};
inline constexpr std::size_t kHeroKit_7A_graphs_count = 8;

// 美 (0xDD) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_DD_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "暴雪"},
    {0x4Bu, 1, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "急冻"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "冰墙"},
    {0x5FEu, 3, 191u, 1u, 4u, 1u, 16u, 5u, 0u, 1u, 0x172Fu, "美_急冻_Projectile", "冰霜冲击枪"},
    {0x622u, 4, 238u, 0u, 0u, 0u, 26u, 1u, 0u, 0u, 0x0u, "", "冰锥"},
    {0x64Au, 5, 53u, 1u, 0u, 0u, 2u, 0u, 0u, 0u, 0x946u, "美_暴雪_Projectile", ""},
    {0xB48u, 6, 120u, 1u, 3u, 0u, 7u, 2u, 0u, 0u, 0x4C85u, "美_暴雪_Projectile", ""},
    {0xD97u, 7, 2u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x3ED3u, 10, 32u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x515Fu, 11, 6u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_DD_graphs_count = 12;

// 黑影 (0x12E) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_12E_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "自动手枪"},
    {0x4Bu, 1, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "黑客入侵"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "病毒侵染"},
    {0xB1Au, 3, 22u, 0u, 0u, 0u, 0u, 0u, 0u, 1u, 0x0u, "", "位移传动"},
    {0xB31u, 4, 79u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", "电磁脉冲"},
    {0xC19u, 5, 206u, 1u, 6u, 0u, 14u, 1u, 0u, 0u, 0x1575u, "黑影_位移传动_Projectile", "相时而动"},
    {0x3918u, 6, 56u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 7, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 8, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x4389u, 9, 56u, 1u, 0u, 0u, 2u, 0u, 0u, 0u, 0x50FEu, "黑影_病毒侵染_Projectile", ""},
    {0x420Cu, 10, 175u, 0u, 0u, 0u, 11u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x51ECu, 11, 34u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_12E_graphs_count = 12;

// 末日铁拳 (0x12F) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_12F_graphs[] = {
    {0x3FE1u, 0, 80u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "裂地重拳"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "悍猛格挡"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "火箭重拳"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "毁天灭地"},
    {0xC51u, 4, 198u, 0u, 2u, 0u, 21u, 4u, 0u, 0u, 0x0u, "", "手炮"},
    {0xD06u, 5, 272u, 0u, 3u, 0u, 40u, 3u, 0u, 0u, 0x0u, "", "最佳防守……"},
    {0xB27u, 6, 127u, 0u, 5u, 0u, 10u, 0u, 0u, 0u, 0x0u, "", "职责：重装"},
    {0xDDDu, 7, 94u, 0u, 1u, 0u, 12u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x374Cu, 8, 146u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51DAu, 10, 49u, 0u, 0u, 0u, 7u, 1u, 1u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_12F_graphs_count = 11;

// 安娜 (0x13B) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_13B_graphs[] = {
    {0x4BE4u, 0, 39u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "麻醉镖"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "生物步枪"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "生物手雷"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "纳米激素"},
    {0xB97u, 4, 60u, 1u, 0u, 0u, 9u, 0u, 0u, 0u, 0x1426u, "安娜_生物手雷_Projectile", "瞄准射击"},
    {0xB9Eu, 5, 154u, 1u, 0u, 0u, 8u, 0u, 0u, 0u, 0x15E9u, "安娜_纳米激素_Projectile", ""},
    {0xBDDu, 6, 78u, 4u, 0u, 0u, 7u, 1u, 0u, 0u, 0x15E8u, "安娜_麻醉镖_Projectile", ""},
    {0xC6Bu, 7, 19u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 9, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51F0u, 10, 37u, 0u, 1u, 0u, 0u, 1u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_13B_graphs_count = 11;

// 奥丽莎 (0x13E) — 13 graphs
inline constexpr HeroKitGraph kHeroKit_13E_graphs[] = {
    {0x3FDEu, 0, 60u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "能量标枪"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "强固防御"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "标枪旋击"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "撼地猛刺"},
    {0x35EEu, 4, 195u, 1u, 2u, 0u, 17u, 1u, 2u, 0u, 0x1846u, "奥丽莎_标枪旋击_Projectile", "强化聚变驱动器"},
    {0x35F1u, 5, 93u, 1u, 0u, 0u, 7u, 2u, 0u, 0u, 0x4147u, "奥丽莎_能量标枪_Projectile", "职责：重装"},
    {0x35EFu, 6, 84u, 0u, 1u, 0u, 10u, 2u, 0u, 5u, 0x0u, "", ""},
    {0x35EDu, 7, 168u, 0u, 3u, 0u, 11u, 1u, 0u, 2u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x35F3u, 9, 26u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 10, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51DDu, 11, 19u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 12, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_13E_graphs_count = 13;

// 布丽吉塔 (0x195) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_195_graphs[] = {
    {0x4411u, 0, 43u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "集结号令"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "鼓舞士气"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "恢复包"},
    {0x8B6u, 3, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "流星飞锤"},
    {0xEE3u, 4, 267u, 1u, 4u, 0u, 21u, 3u, 0u, 0u, 0x6A33u, "布丽吉塔_屏障护盾_Projectile", "火箭连枷"},
    {0x12D8u, 5, 36u, 0u, 0u, 0u, 6u, 2u, 0u, 0u, 0x0u, "", "屏障护盾"},
    {0x1259u, 6, 215u, 0u, 3u, 0u, 46u, 9u, 0u, 0u, 0x0u, "", "能量盾击"},
    {0xEDDu, 7, 119u, 0u, 1u, 0u, 19u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x12BEu, 8, 68u, 0u, 0u, 0u, 3u, 3u, 0u, 1u, 0x0u, "", ""},
    {0x145Bu, 9, 41u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51F2u, 10, 51u, 0u, 2u, 1u, 2u, 1u, 0u, 0u, 0x6AB6u, "布丽吉塔_slot10_Spawned", ""},
};
inline constexpr std::size_t kHeroKit_195_graphs_count = 11;

// 莫伊拉 (0x1A2) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_1A2_graphs[] = {
    {0x3E52u, 0, 61u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "生化之触"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "辅助攻击模式"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "生化之球"},
    {0x4Bu, 3, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "消散"},
    {0xF7Cu, 4, 169u, 0u, 3u, 0u, 17u, 4u, 0u, 0u, 0x0u, "", "聚合射线"},
    {0x1007u, 5, 232u, 0u, 3u, 0u, 12u, 3u, 0u, 0u, 0x0u, "", ""},
    {0x10E4u, 6, 265u, 5u, 0u, 0u, 39u, 2u, 0u, 0u, 0x1E61u, "莫伊拉_生化之球_Projectile", ""},
    {0x1166u, 7, 14u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x3635u, 8, 3u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x374Du, 9, 29u, 0u, 1u, 0u, 5u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 10, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5164u, 11, 35u, 0u, 0u, 0u, 2u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_1A2_graphs_count = 12;

// 破坏球 (0x1CA) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_1CA_graphs[] = {
    {0x39BEu, 0, 71u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "四联火炮"},
    {0x1203u, 1, 243u, 0u, 3u, 0u, 26u, 2u, 0u, 0u, 0x0u, "", "地雷禁区"},
    {0x33u, 2, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "工程抓钩"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "动力铁球"},
    {0x4Bu, 4, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "重力坠击"},
    {0x1268u, 5, 37u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", "感应护盾"},
    {0x14E4u, 6, 229u, 0u, 2u, 0u, 46u, 7u, 0u, 0u, 0x0u, "", "职责：重装"},
    {0x160Au, 7, 158u, 0u, 1u, 0u, 20u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x1517u, 8, 82u, 5u, 0u, 0u, 11u, 2u, 0u, 0u, 0x2578u, "破坏球_地雷禁区_Projectile", ""},
    {0x4EBCu, 9, 71u, 0u, 1u, 0u, 4u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 10, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51E2u, 11, 13u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_1CA_graphs_count = 12;

// 索杰恩 (0x1EC) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_1EC_graphs[] = {
    {0x3505u, 0, 54u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "机动滑铲"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "干扰弹"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "电磁炮"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "充能射击"},
    {0x142Eu, 4, 81u, 0u, 2u, 0u, 6u, 1u, 0u, 0u, 0x0u, "", "机体超频"},
    {0x1E6Fu, 5, 345u, 2u, 1u, 0u, 45u, 21u, 0u, 0u, 0x31EFu, "索杰恩_机动滑铲_Projectile", ""},
    {0x1441u, 6, 130u, 4u, 0u, 0u, 20u, 7u, 0u, 0u, 0x31EFu, "索杰恩_机动滑铲_Projectile", ""},
    {0x2159u, 7, 178u, 0u, 4u, 0u, 26u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51EBu, 10, 13u, 0u, 0u, 0u, 2u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_1EC_graphs_count = 11;

// 艾什 (0x200) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_200_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "短筒猎枪"},
    {0x4Bu, 1, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "召唤鲍勃"},
    {0x14FDu, 2, 102u, 1u, 3u, 0u, 10u, 0u, 0u, 0u, 0x2533u, "艾什_延时雷管_Projectile", "延时雷管"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "毒蛇"},
    {0x14FFu, 4, 56u, 0u, 0u, 0u, 10u, 2u, 0u, 0u, 0x0u, "", "瞄准射击"},
    {0x1513u, 5, 161u, 2u, 0u, 0u, 15u, 3u, 0u, 0u, 0x2B61u, "艾什_短筒猎枪_Projectile", ""},
    {0x1536u, 6, 104u, 1u, 0u, 0u, 17u, 1u, 0u, 0u, 0x43C0u, "艾什_召唤鲍勃_Projectile", ""},
    {0x35A6u, 7, 57u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 11, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51E3u, 12, 43u, 0u, 1u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_200_graphs_count = 12;

// 回声 (0x206) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_206_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "黏性炸弹"},
    {0x43u, 1, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "人格复制"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "三角射击"},
    {0x1BB6u, 3, 102u, 0u, 0u, 0u, 7u, 3u, 0u, 0u, 0x0u, "", "飞行"},
    {0x19EBu, 4, 255u, 0u, 1u, 1u, 29u, 3u, 0u, 0u, 0x0u, "", "聚焦光线"},
    {0x1FBDu, 5, 124u, 0u, 1u, 0u, 9u, 2u, 0u, 0u, 0x0u, "", "滑翔"},
    {0x1C36u, 6, 50u, 1u, 0u, 0u, 1u, 0u, 0u, 0u, 0x2CBAu, "回声_黏性炸弹_Projectile", ""},
    {0x1DFCu, 7, 90u, 0u, 0u, 0u, 11u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x440Fu, 9, 41u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51E6u, 10, 27u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_206_graphs_count = 11;

// 巴蒂斯特 (0x221) — 10 graphs
inline constexpr HeroKitGraph kHeroKit_221_graphs[] = {
    {0x331Fu, 0, 52u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "愈合冲击"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "维生力场"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "增幅矩阵"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "生化榴弹枪"},
    {0x1761u, 4, 72u, 1u, 0u, 0u, 15u, 1u, 0u, 0u, 0x29A8u, "巴蒂斯特_slot4_Projectile", "辅助攻击模式"},
    {0x19A5u, 5, 79u, 0u, 1u, 0u, 5u, 1u, 0u, 0u, 0x0u, "", "动力战靴"},
    {0x1902u, 6, 158u, 0u, 1u, 0u, 24u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x1983u, 7, 167u, 0u, 1u, 0u, 20u, 5u, 0u, 1u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51F1u, 9, 40u, 2u, 0u, 0u, 0u, 2u, 0u, 0u, 0x4014u, "巴蒂斯特_生化榴弹枪_Projectile", ""},
};
inline constexpr std::size_t kHeroKit_221_graphs_count = 10;

// 雾子 (0x231) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_231_graphs[] = {
    {0x4BE5u, 0, 45u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "狐"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "符"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "锥"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "瞬"},
    {0x8B6u, 4, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "铃"},
    {0x30DBu, 5, 219u, 0u, 0u, 0u, 36u, 0u, 0u, 0u, 0x0u, "", "攀"},
    {0x30D8u, 6, 88u, 1u, 0u, 0u, 18u, 0u, 0u, 0u, 0x3FD3u, "雾子_铃_Projectile", ""},
    {0x30DAu, 7, 71u, 0u, 0u, 0u, 9u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x30D9u, 8, 78u, 0u, 0u, 0u, 6u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 9, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5163u, 10, 64u, 2u, 0u, 0u, 2u, 1u, 0u, 1u, 0x6606u, "雾子_slot10_Projectile", ""},
    {0x5016u, 11, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_231_graphs_count = 12;

// 渣客女王 (0x236) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_236_graphs[] = {
    {0x3A21u, 0, 59u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "锯齿利刃（格雷西）"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "命令怒吼"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "散弹枪"},
    {0x21F7u, 3, 274u, 0u, 2u, 0u, 25u, 9u, 0u, 2u, 0x0u, "", "血斩"},
    {0x222Du, 4, 122u, 0u, 2u, 0u, 5u, 2u, 0u, 0u, 0x0u, "", "轰翻天"},
    {0x2209u, 5, 197u, 1u, 5u, 0u, 13u, 1u, 0u, 0u, 0x458Cu, "渣客女王_血斩_Projectile", "狂血奔涌"},
    {0x215Fu, 6, 269u, 2u, 3u, 0u, 20u, 5u, 0u, 0u, 0x3555u, "渣客女王_锯齿利刃（格雷西）_Projectile", "职责：重装"},
    {0x2212u, 7, 135u, 0u, 1u, 0u, 7u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x2979u, 8, 78u, 0u, 1u, 0u, 5u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 10, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51DBu, 11, 49u, 0u, 1u, 0u, 3u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_236_graphs_count = 12;

// 西格玛 (0x23B) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_23B_graphs[] = {
    {0x34C3u, 0, 87u, 0u, 0u, 0u, 0u, 0u, 0u, 1u, 0x0u, "", "动能俘获"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "质量吸附"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "引力乱流"},
    {0x1B55u, 3, 183u, 0u, 0u, 0u, 10u, 3u, 0u, 0u, 0x0u, "", "超能之球"},
    {0x1869u, 4, 111u, 0u, 2u, 0u, 12u, 2u, 0u, 0u, 0x0u, "", "实验屏障"},
    {0x1D02u, 5, 197u, 1u, 2u, 0u, 36u, 2u, 1u, 0u, 0x2CBAu, "回声_黏性炸弹_Projectile", "职责：重装"},
    {0x1BBBu, 6, 161u, 4u, 0u, 0u, 21u, 8u, 0u, 0u, 0x18B7u, "西格玛_质量吸附_Projectile", ""},
    {0x1E41u, 7, 236u, 0u, 0u, 0u, 25u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x43u, 8, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 10, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x51E0u, 11, 59u, 0u, 1u, 0u, 6u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_23B_graphs_count = 12;

// 拉玛刹 (0x28D) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_28D_graphs[] = {
    {0x3C5Au, 0, 51u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "虚空加速器（智械形态）"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "猛拳（天罚形态）"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "虚空屏障（智械形态）"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "天罚形态"},
    {0x20B1u, 4, 139u, 0u, 0u, 0u, 14u, 1u, 0u, 0u, 0x0u, "", "铁臂（天罚形态）"},
    {0x20B9u, 5, 107u, 0u, 4u, 0u, 9u, 0u, 0u, 3u, 0x0u, "", "吞噬漩涡"},
    {0x20CFu, 6, 326u, 0u, 1u, 0u, 46u, 3u, 2u, 0u, 0x0u, "", "诛"},
    {0x2948u, 7, 125u, 2u, 1u, 0u, 12u, 1u, 0u, 0u, 0x3523u, "拉玛刹_吞噬漩涡_Projectile", "职责：重装"},
    {0x2FB6u, 8, 141u, 0u, 2u, 0u, 11u, 3u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51DEu, 10, 28u, 1u, 0u, 0u, 2u, 0u, 0u, 0u, 0x663Fu, "拉玛刹_slot10_Projectile", ""},
};
inline constexpr std::size_t kHeroKit_28D_graphs_count = 11;

// 生命之梭 (0x291) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_291_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "愈疗灵花"},
    {0x4Bu, 1, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "棘刺箭雨"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "花瓣平台"},
    {0x21EFu, 3, 133u, 0u, 0u, 0u, 17u, 1u, 0u, 0u, 0x0u, "", "回春疾行"},
    {0x2219u, 4, 97u, 1u, 0u, 0u, 10u, 1u, 0u, 0u, 0x450Fu, "生命之梭_花瓣平台_Projectile", "生命之握"},
    {0x220Eu, 5, 40u, 0u, 0u, 0u, 2u, 0u, 0u, 0u, 0x0u, "", "生命之树"},
    {0x36A4u, 6, 200u, 0u, 0u, 0u, 20u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x36A2u, 7, 78u, 0u, 1u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x4646u, 8, 38u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51F4u, 10, 63u, 2u, 1u, 0u, 5u, 0u, 0u, 0u, 0x4809u, "生命之梭_slot10_Projectile", ""},
};
inline constexpr std::size_t kHeroKit_291_graphs_count = 11;

// 毛加 (0x30A) — 10 graphs
inline constexpr HeroKitGraph kHeroKit_30A_graphs[] = {
    {0x3FE0u, 0, 59u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "蛮力冲撞"},
    {0x4Bu, 1, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "心脏过载"},
    {0x33u, 2, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "笼中斗"},
    {0x3689u, 3, 51u, 0u, 3u, 0u, 4u, 0u, 0u, 1u, 0x0u, "", "燃火链式机枪（老枪）"},
    {0x3688u, 4, 287u, 0u, 4u, 0u, 33u, 2u, 0u, 0u, 0x0u, "", "爆烈链式机枪（恰恰）"},
    {0x186Cu, 5, 83u, 0u, 1u, 0u, 6u, 1u, 0u, 0u, 0x0u, "", "狂战士"},
    {0x3693u, 6, 81u, 0u, 0u, 0u, 12u, 1u, 0u, 0u, 0x0u, "", "职责：重装"},
    {0x43u, 7, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51DCu, 9, 33u, 0u, 0u, 0u, 4u, 0u, 0u, 1u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_30A_graphs_count = 10;

// 伊拉锐 (0x31C) — 10 graphs
inline constexpr HeroKitGraph kHeroKit_31C_graphs[] = {
    {0x33u, 0, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "烈日冲击"},
    {0x4Bu, 1, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "治疗光塔"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "桎梏灼日"},
    {0x3DF4u, 3, 102u, 1u, 0u, 0u, 12u, 0u, 0u, 0u, 0x4B4Au, "伊拉锐_治疗光塔_Projectile", "阳焰步枪"},
    {0x3B38u, 4, 105u, 0u, 1u, 0u, 10u, 2u, 0u, 0u, 0x0u, "", "辅助攻击模式"},
    {0x3A9Au, 5, 22u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x3CABu, 6, 120u, 1u, 0u, 0u, 9u, 2u, 0u, 0u, 0x4AC0u, "伊拉锐_桎梏灼日_Projectile", ""},
    {0x4659u, 7, 44u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x51F3u, 9, 81u, 0u, 2u, 0u, 5u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_31C_graphs_count = 10;

// 弗蕾娅 (0x32A) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_32A_graphs[] = {
    {0x5385u, 0, 102u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "速射弩"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "瞄准射击"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "疾冲"},
    {0x4Bu, 3, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "上升气流"},
    {0x4993u, 4, 188u, 0u, 0u, 0u, 6u, 9u, 0u, 0u, 0x0u, "", "流星索"},
    {0x3C1Du, 5, 200u, 0u, 0u, 0u, 30u, 7u, 0u, 0u, 0x0u, "", "赏金狩猎"},
    {0x4E2Bu, 6, 82u, 0u, 0u, 0u, 5u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x4F14u, 7, 95u, 1u, 0u, 0u, 9u, 7u, 0u, 0u, 0x5E3Du, "弗蕾娅_流星索_Projectile", ""},
    {0x4DA6u, 8, 53u, 0u, 0u, 0u, 5u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x53FFu, 10, 40u, 0u, 1u, 0u, 5u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_32A_graphs_count = 11;

// 探奇 (0x32B) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_32B_graphs[] = {
    {0x4BE8u, 0, 65u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "智能挖掘钻"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "钻地"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "钻头突刺"},
    {0x4587u, 3, 118u, 1u, 2u, 0u, 7u, 1u, 0u, 0u, 0x5AFFu, "探奇_猛钻_Projectile", "地壳震击"},
    {0x4335u, 4, 184u, 0u, 2u, 0u, 14u, 3u, 0u, 0u, 0x0u, "", "猛钻"},
    {0x4284u, 5, 279u, 0u, 1u, 0u, 34u, 6u, 0u, 0u, 0x0u, "", "探险家的决心"},
    {0x4266u, 6, 129u, 0u, 4u, 0u, 6u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 7, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x3C38u, 8, 70u, 0u, 1u, 0u, 9u, 1u, 0u, 1u, 0x0u, "", ""},
    {0x53F5u, 9, 3u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x515Eu, 10, 42u, 0u, 0u, 0u, 1u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_32B_graphs_count = 11;

// 骇灾 (0x362) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_362_graphs[] = {
    {0x443Au, 0, 58u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "千针雨"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "骨刺"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "尖刺护体"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "狂跃"},
    {0x43BFu, 4, 176u, 1u, 0u, 0u, 10u, 6u, 0u, 0u, 0x50BCu, "骇灾_尖刺护体_Projectile", "尖刺墙"},
    {0x478Du, 5, 177u, 0u, 2u, 0u, 13u, 5u, 0u, 0u, 0x0u, "", "翻越"},
    {0x4BCFu, 6, 146u, 1u, 0u, 0u, 13u, 2u, 0u, 0u, 0x5986u, "骇灾_尖刺墙_Projectile", "职责：重装"},
    {0x43FAu, 7, 122u, 0u, 0u, 0u, 8u, 8u, 0u, 0u, 0x0u, "", ""},
    {0x4A72u, 8, 119u, 1u, 0u, 0u, 10u, 4u, 0u, 0u, 0x6195u, "骇灾_千针雨_Projectile", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x522Fu, 10, 30u, 0u, 1u, 0u, 4u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_362_graphs_count = 11;

// 朱诺 (0x365) — 13 graphs
inline constexpr HeroKitGraph kHeroKit_365_graphs[] = {
    {0x4Bu, 0, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "医疗冲击枪"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "脉冲星飞雷"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "滑翔推进"},
    {0x3DCEu, 3, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", "超能环域"},
    {0x8B6u, 4, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "轨道射线"},
    {0x4448u, 5, 52u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "火星套靴"},
    {0x4695u, 6, 197u, 2u, 0u, 0u, 21u, 3u, 0u, 0u, 0x534Fu, "朱诺_脉冲星飞雷_Projectile", ""},
    {0x47B7u, 7, 153u, 0u, 0u, 0u, 10u, 3u, 0u, 0u, 0x0u, "", ""},
    {0x4857u, 8, 48u, 4u, 0u, 0u, 3u, 0u, 0u, 0u, 0x5530u, "朱诺_超能环域_Projectile", ""},
    {0x4A44u, 9, 39u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x4441u, 10, 131u, 0u, 0u, 0u, 13u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x522Eu, 11, 29u, 0u, 0u, 0u, 5u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 12, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_365_graphs_count = 13;

// 无漾 (0x3C3) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_3C3_graphs[] = {
    {0x5498u, 0, 74u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "玄武杖"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "翻江浪"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "飞流步"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "养神泉"},
    {0x52D8u, 4, 238u, 0u, 2u, 0u, 12u, 2u, 0u, 0u, 0x0u, "", "惊涛破"},
    {0x523Du, 5, 137u, 0u, 0u, 0u, 11u, 4u, 0u, 0u, 0x0u, "", ""},
    {0x5219u, 6, 114u, 0u, 0u, 0u, 12u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x52E9u, 7, 237u, 0u, 4u, 0u, 12u, 4u, 0u, 1u, 0x0u, "", ""},
    {0x5807u, 8, 25u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 9, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5623u, 10, 5u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_3C3_graphs_count = 11;

// 斩仇 (0x472) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_472_graphs[] = {
    {0x5174u, 0, 73u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "旋风疾步"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "飞空斩击"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "帕拉蒂尼之牙"},
    {0x8B6u, 3, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "招架姿态"},
    {0x5176u, 4, 242u, 1u, 0u, 0u, 25u, 4u, 0u, 0u, 0x0u, "", "锋锐剑气"},
    {0x529Cu, 5, 283u, 0u, 4u, 0u, 43u, 5u, 0u, 0u, 0x0u, "", "斩地巨剑"},
    {0x5175u, 6, 144u, 1u, 0u, 0u, 14u, 0u, 0u, 0u, 0x62A0u, "斩仇_飞空斩击_Projectile", "越战越勇"},
    {0x52F0u, 7, 224u, 0u, 4u, 0u, 22u, 7u, 0u, 0u, 0x0u, "", ""},
    {0x572Fu, 8, 92u, 0u, 3u, 0u, 4u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x53F3u, 9, 75u, 0u, 1u, 0u, 1u, 0u, 0u, 1u, 0x0u, "", ""},
    {0x5B17u, 10, 5u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_472_graphs_count = 11;

// 金驭 (0x4C4) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_4C4_graphs[] = {
    {0x4Bu, 0, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "光子马格南"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "屏障阵列"},
    {0x43u, 2, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "音速斥力场"},
    {0x3DCEu, 3, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", "爆能水晶"},
    {0x8B6u, 4, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "全景牢笼"},
    {0x5546u, 5, 52u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "护盾重构"},
    {0x552Bu, 6, 51u, 0u, 1u, 0u, 2u, 0u, 0u, 0u, 0x0u, "", "职责：重装"},
    {0x58CBu, 7, 124u, 0u, 1u, 0u, 8u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x57D2u, 8, 67u, 0u, 1u, 0u, 5u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5849u, 9, 76u, 1u, 0u, 0u, 6u, 0u, 0u, 0u, 0x686Bu, "金驭_爆能水晶_Projectile", ""},
    {0x57C4u, 10, 50u, 1u, 0u, 0u, 3u, 0u, 0u, 0u, 0x6861u, "金驭_全景牢笼_Projectile", ""},
    {0x58FBu, 11, 15u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_4C4_graphs_count = 12;

// 埃姆雷 (0x4D8) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_4D8_graphs[] = {
    {0x56D2u, 0, 74u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "合成连发步枪"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "瞄准射击"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "虹吸冲击枪"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "赛博手雷"},
    {0x56FBu, 4, 220u, 1u, 1u, 0u, 15u, 8u, 0u, 0u, 0x68EEu, "埃姆雷_虹吸冲击枪_Projectile", "覆盖协议"},
    {0x56EDu, 5, 86u, 2u, 1u, 0u, 11u, 2u, 0u, 0u, 0x6909u, "埃姆雷_赛博手雷_Projectile", "机变体征"},
    {0x5732u, 6, 226u, 2u, 0u, 0u, 12u, 10u, 0u, 0u, 0x6AF7u, "埃姆雷_覆盖协议_Projectile", ""},
    {0x57A9u, 7, 67u, 0u, 1u, 0u, 6u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 9, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x56D3u, 10, 44u, 0u, 1u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_4D8_graphs_count = 11;

// 安燃 (0x4DD) — 11 graphs
inline constexpr HeroKitGraph kHeroKit_4DD_graphs[] = {
    {0x578Au, 0, 82u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "朱雀扇"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "煽火风"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "怒炎冲"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "熠闪舞"},
    {0x8B6u, 4, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", "朱羽焚"},
    {0x5862u, 5, 151u, 0u, 1u, 0u, 20u, 3u, 0u, 0u, 0x0u, "", "朱魂返"},
    {0x58C5u, 6, 225u, 0u, 3u, 0u, 32u, 6u, 0u, 0u, 0x0u, "", "焚身焰"},
    {0x5922u, 7, 400u, 0u, 4u, 0u, 55u, 11u, 0u, 2u, 0x0u, "", ""},
    {0x5798u, 8, 34u, 0u, 0u, 0u, 3u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5ACDu, 9, 9u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x3DCEu, 10, 6u, 0u, 0u, 0u, 1u, 0u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_4DD_graphs_count = 11;

// 瑞稀 (0x4E3) — 12 graphs
inline constexpr HeroKitGraph kHeroKit_4E3_graphs[] = {
    {0x58EBu, 0, 73u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "御魂镰刃"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "疗魂斗笠"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "缚魂锁链"},
    {0x58F0u, 3, 153u, 0u, 0u, 1u, 20u, 3u, 0u, 0u, 0x6D27u, "瑞稀_替魂纸人_Spawned", "替魂纸人"},
    {0x5AD7u, 4, 214u, 0u, 2u, 0u, 45u, 10u, 0u, 0u, 0x0u, "", "护魂结界"},
    {0x5A08u, 5, 136u, 1u, 1u, 0u, 16u, 1u, 0u, 0u, 0x6CEFu, "瑞稀_疗魂斗笠_Projectile", "安魂灵气"},
    {0x5B7Au, 6, 93u, 0u, 0u, 0u, 5u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x43u, 7, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x8B6u, 8, 43u, 0u, 0u, 0u, 8u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5016u, 9, 179u, 0u, 0u, 0u, 28u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x58EDu, 10, 15u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", ""},
    {0x5AB8u, 11, 91u, 0u, 0u, 0u, 5u, 1u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_4E3_graphs_count = 12;

// 飞天猫 (0x516) — 10 graphs
inline constexpr HeroKitGraph kHeroKit_516_graphs[] = {
    {0x59DDu, 0, 70u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, "", "生物猫爪弹"},
    {0x33u, 1, 125u, 0u, 8u, 0u, 13u, 0u, 0u, 6u, 0x0u, "", "咻咻飞"},
    {0x4Bu, 2, 214u, 0u, 0u, 0u, 44u, 2u, 0u, 0u, 0x0u, "", "救生索"},
    {0x43u, 3, 112u, 0u, 3u, 0u, 7u, 1u, 0u, 0u, 0x0u, "", "呼噜噜"},
    {0x59DCu, 4, 95u, 0u, 0u, 0u, 5u, 5u, 0u, 0u, 0x0u, "", "猫猫劫"},
    {0x59E0u, 5, 164u, 0u, 0u, 0u, 19u, 4u, 0u, 0u, 0x0u, "", "喷气背包"},
    {0x5A8Fu, 6, 281u, 0u, 2u, 0u, 38u, 5u, 0u, 1u, 0x0u, "", ""},
    {0x5A7Eu, 7, 113u, 0u, 4u, 0u, 10u, 1u, 0u, 0u, 0x0u, "", ""},
    {0x5B7Bu, 8, 300u, 0u, 3u, 0u, 41u, 2u, 0u, 0u, 0x0u, "", ""},
    {0x5BAFu, 9, 89u, 0u, 2u, 0u, 5u, 2u, 0u, 0u, 0x0u, "", ""},
};
inline constexpr std::size_t kHeroKit_516_graphs_count = 10;

inline constexpr HeroKit kHeroKits[] = {
    {0x2u, "死神", 14u, false, true, true, kHeroKit_2_graphs},
    {0x3u, "猎空", 11u, false, true, false, kHeroKit_3_graphs},
    {0x4u, "天使", 12u, false, false, true, kHeroKit_4_graphs},
    {0x5u, "半藏", 12u, false, true, false, kHeroKit_5_graphs},
    {0x6u, "托比昂", 11u, false, true, true, kHeroKit_6_graphs},
    {0x7u, "莱因哈特", 12u, false, false, true, kHeroKit_7_graphs},
    {0x8u, "法老之鹰", 12u, false, true, true, kHeroKit_8_graphs},
    {0x9u, "温斯顿", 10u, false, false, true, kHeroKit_9_graphs},
    {0xAu, "黑百合", 11u, false, true, false, kHeroKit_A_graphs},
    {0x15u, "堡垒", 12u, false, true, false, kHeroKit_15_graphs},
    {0x16u, "秩序之光", 10u, false, false, true, kHeroKit_16_graphs},
    {0x20u, "禅雅塔", 10u, false, false, true, kHeroKit_20_graphs},
    {0x29u, "源氏", 12u, true, true, false, kHeroKit_29_graphs},
    {0x40u, "路霸", 11u, true, true, false, kHeroKit_40_graphs},
    {0x42u, "卡西迪", 12u, false, true, false, kHeroKit_42_graphs},
    {0x65u, "狂鼠", 11u, false, true, false, kHeroKit_65_graphs},
    {0x68u, "查莉娅", 10u, false, true, true, kHeroKit_68_graphs},
    {0x6Eu, "士兵：76", 13u, false, true, true, kHeroKit_6E_graphs},
    {0x79u, "卢西奥", 11u, false, true, false, kHeroKit_79_graphs},
    {0x7Au, "D.Va", 8u, true, false, false, kHeroKit_7A_graphs},
    {0xDDu, "美", 12u, false, true, false, kHeroKit_DD_graphs},
    {0x12Eu, "黑影", 12u, false, true, true, kHeroKit_12E_graphs},
    {0x12Fu, "末日铁拳", 11u, true, false, true, kHeroKit_12F_graphs},
    {0x13Bu, "安娜", 11u, false, true, false, kHeroKit_13B_graphs},
    {0x13Eu, "奥丽莎", 13u, true, true, false, kHeroKit_13E_graphs},
    {0x195u, "布丽吉塔", 11u, false, true, true, kHeroKit_195_graphs},
    {0x1A2u, "莫伊拉", 12u, false, true, false, kHeroKit_1A2_graphs},
    {0x1CAu, "破坏球", 12u, false, true, true, kHeroKit_1CA_graphs},
    {0x1ECu, "索杰恩", 11u, false, true, false, kHeroKit_1EC_graphs},
    {0x200u, "艾什", 12u, false, true, false, kHeroKit_200_graphs},
    {0x206u, "回声", 11u, false, true, false, kHeroKit_206_graphs},
    {0x221u, "巴蒂斯特", 10u, false, true, true, kHeroKit_221_graphs},
    {0x231u, "雾子", 12u, false, true, false, kHeroKit_231_graphs},
    {0x236u, "渣客女王", 12u, false, true, true, kHeroKit_236_graphs},
    {0x23Bu, "西格玛", 12u, true, true, false, kHeroKit_23B_graphs},
    {0x28Du, "拉玛刹", 11u, true, true, false, kHeroKit_28D_graphs},
    {0x291u, "生命之梭", 11u, false, true, true, kHeroKit_291_graphs},
    {0x30Au, "毛加", 10u, false, false, false, kHeroKit_30A_graphs},
    {0x31Cu, "伊拉锐", 10u, false, true, false, kHeroKit_31C_graphs},
    {0x32Au, "弗蕾娅", 11u, false, true, false, kHeroKit_32A_graphs},
    {0x32Bu, "探奇", 11u, false, true, true, kHeroKit_32B_graphs},
    {0x362u, "骇灾", 11u, false, true, false, kHeroKit_362_graphs},
    {0x365u, "朱诺", 13u, false, true, false, kHeroKit_365_graphs},
    {0x3C3u, "无漾", 11u, false, false, false, kHeroKit_3C3_graphs},
    {0x472u, "斩仇", 11u, false, true, false, kHeroKit_472_graphs},
    {0x4C4u, "金驭", 12u, false, true, false, kHeroKit_4C4_graphs},
    {0x4D8u, "埃姆雷", 11u, false, true, false, kHeroKit_4D8_graphs},
    {0x4DDu, "安燃", 11u, false, false, false, kHeroKit_4DD_graphs},
    {0x4E3u, "瑞稀", 12u, false, true, false, kHeroKit_4E3_graphs},
    {0x516u, "飞天猫", 10u, false, false, true, kHeroKit_516_graphs},
};
inline constexpr std::size_t kHeroKitCount = 50;

inline const HeroKit* FindHeroKit(uint32_t hero_id) noexcept {
    for (const auto& k : kHeroKits) if (k.hero_id == hero_id) return &k;
    return nullptr;
}

inline bool HeroHasDeflect(uint32_t hero_id) noexcept {
    const auto* k = FindHeroKit(hero_id); return k && k->has_deflect;
}

inline bool HeroHasProjectileWeapon(uint32_t hero_id) noexcept {
    const auto* k = FindHeroKit(hero_id); return k && k->has_projectile_weapon;
}

} // namespace sdk
} // namespace ow
