// ============================================================================
// AUTO-GENERATED by scripts/generate_sdk_v2.py
// DO NOT EDIT BY HAND. Source of truth:
//   - blueprint_editor/output/var_dictionary.json (statescript var names)
//   - output/dump_json/heroes.json + loadouts.json (CASC dump)
// Regenerate: python3 scripts/generate_sdk_v2.py
// ============================================================================
#pragma once

#include <cstdint>
#include <cstddef>

// namedump.hpp — Hero ID → display name (zh-CN)
// 50 playable heroes (is_hero=true) from CASC STUHero

namespace ow {
namespace sdk {

/// Hero metadata: id + display name (zh-CN) + attributes from CASC STUHero
struct HeroInfo {
    uint32_t    id;          // STUHero hero_id (e.g. 0x2 = Reaper)
    const char* name_zhCN;   // 中文名 (display)
    const char* gender;      // Male / Female / Other
    const char* size;        // Normal / Large / Small
    const char* color;       // hex color used by HUD
};

inline constexpr HeroInfo kHeroes[] = {
    {0x2u, "死神", "Male", "Normal", "#5E001A"},
    {0x3u, "猎空", "Female", "Normal", "#DE7A00"},
    {0x4u, "天使", "Female", "Normal", "#FAF2AD"},
    {0x5u, "半藏", "Male", "Normal", "#B2A865"},
    {0x6u, "托比昂", "Male", "Normal", "#BA4C3F"},
    {0x7u, "莱因哈特", "Male", "Large", "#7C8B8C"},
    {0x8u, "法老之鹰", "Female", "Normal", "#0058BC"},
    {0x9u, "温斯顿", "Male", "Large", "#8F92AE"},
    {0xAu, "黑百合", "Female", "Normal", "#8B3F8F"},
    {0x15u, "堡垒", "Generic", "Large", "#5B7351"},
    {0x16u, "秩序之光", "Female", "Normal", "#76B4C9"},
    {0x20u, "禅雅塔", "Male", "Normal", "#FCEE5A"},
    {0x29u, "源氏", "Male", "Normal", "#80FB00"},
    {0x40u, "路霸", "Male", "Large", "#AE6F1C"},
    {0x42u, "卡西迪", "Male", "Normal", "#A62927"},
    {0x65u, "狂鼠", "Male", "Normal", "#F7B217"},
    {0x68u, "查莉娅", "Female", "Normal", "#F65EA6"},
    {0x6Eu, "士兵：76", "Male", "Normal", "#445275"},
    {0x79u, "卢西奥", "Male", "Normal", "#67C519"},
    {0x7Au, "D.Va", "Female", "Large", "#FC79BD"},
    {0xDDu, "美", "Female", "Normal", "#469AF0"},
    {0x12Eu, "黑影", "Female", "Normal", "#5128A9"},
    {0x12Fu, "末日铁拳", "Male", "Normal", "#661E0F"},
    {0x13Bu, "安娜", "Female", "Normal", "#48699E"},
    {0x13Eu, "奥丽莎", "Female", "Large", "#106F04"},
    {0x195u, "布丽吉塔", "Female", "Normal", "#72332A"},
    {0x1A2u, "莫伊拉", "Female", "Normal", "#804BE5"},
    {0x1CAu, "破坏球", "Male", "Large", "#E2790A"},
    {0x1ECu, "索杰恩", "Female", "Normal", "#D73E2C"},
    {0x200u, "艾什", "Female", "Normal", "#3E3C3A"},
    {0x206u, "回声", "Female", "Normal", "#89C8FF"},
    {0x221u, "巴蒂斯特", "Male", "Normal", "#28A5C3"},
    {0x231u, "雾子", "Female", "Small", "#D04656"},
    {0x236u, "渣客女王", "Female", "Normal", "#579FCF"},
    {0x23Bu, "西格玛", "Male", "Large", "#7C8B8C"},
    {0x28Du, "拉玛刹", "Male", "Normal", "#7D55C7"},
    {0x291u, "生命之梭", "Male", "Normal", "#E1A5BA"},
    {0x30Au, "毛加", "Male", "Large", "#DB4216"},
    {0x31Cu, "伊拉锐", "Female", "Normal", "#A58C54"},
    {0x32Au, "弗蕾娅", "Female", "Normal", "#3F93FF"},
    {0x32Bu, "探奇", "Generic", "Normal", "#79614E"},
    {0x362u, "骇灾", "Male", "Large", "#985EC0"},
    {0x365u, "朱诺", "Female", "Normal", "#721FA3"},
    {0x3C3u, "无漾", "Male", "Normal", "#4C7FEF"},
    {0x472u, "斩仇", "Female", "Normal", "#961A1C"},
    {0x4C4u, "金驭", "Female", "Normal", "#69DEEF"},
    {0x4D8u, "埃姆雷", "Male", "Normal", "#C70C0C"},
    {0x4DDu, "安燃", "Female", "Small", "#E81A05"},
    {0x4E3u, "瑞稀", "Male", "Normal", "#9AFFC7"},
    {0x516u, "飞天猫", "Female", "Normal", "#C9CDD1"},
};
inline constexpr std::size_t kHeroCount = 50;

/// Lookup by id. Returns nullptr if not found.
inline const HeroInfo* FindHero(uint32_t id) noexcept {
    for (const auto& h : kHeroes) {
        if (h.id == id) return &h;
    }
    return nullptr;
}

/// Get display name (zh-CN). Returns "?" if unknown.
inline const char* HeroName(uint32_t id) noexcept {
    const auto* h = FindHero(id);
    return h ? h->name_zhCN : "?";
}

/// True iff id is a known playable hero.
inline bool IsPlayableHero(uint32_t id) noexcept {
    return FindHero(id) != nullptr;
}

/// Iterator helpers for range-for / std::for_each.
inline const HeroInfo* HeroesBegin() noexcept { return kHeroes; }
inline const HeroInfo* HeroesEnd()   noexcept { return kHeroes + kHeroCount; }

} // namespace sdk
} // namespace ow
